### ISSUE TITLE
How to use NBT library to Set Slot packet?

### ISSUE THREAD

**Issue by zLupa** [Tnze/go-mc#101]
Hello, I'm trying to send a Set Slot packet using go-mc/net.
The problem is, I can't send an NBT using the NBT library to change the name of the item.
The item appears normal but the name doesn't change

This is what I'm trying to do:
```go
type Display struct {
	Name string `nbt:"name"`
}

type Compound struct {
	Display Display `nbt:"display"`
}

CustomName := Compound{
	Display: Display{Name: "Custom name"},
}

conn.WritePacket(pk.Marshal(0x15,
	/* Other fields here are working, NBT tags aren't */
	pk.NBT(CustomName),
))

```

I tried to follow the example provided in NBT library about the "hello world compound" but doesn't seems to work in my case.
Also, I don't know if it's correct but in the example, I don't see where I can provide the name of the compound for example, "hello world"

**Comment by Tnze** [comment]
I've added an example of `SetSlot` into `packet_test.go`.
To change the name of the compound you can use the parameter `optionalTagName` of `nbt.Marshal()` or `Encode()`.
A minor modification has been applied to `pk.NBT()` to support this parameter as well :)

**Comment by Tnze** [comment]
Looks like the `Name` Tag should be `Name` but not `name`.

```go
type Display struct {
	Name string `nbt:"Name"`
}
```
or just
```go
type Display struct {
	Name string
}
```

**Comment by zLupa** [comment]
> Looks like the `Name` Tag should be `Name` rather than `name`.
> 
> ```go
> type Display struct {
> 	Name string `nbt:"Name"`
> }
> ```
> 
> or just
> 
> ```go
> type Display struct {
> 	Name string
> }
> ```

Thanks, that solved, by one capital letter lmao.
