### ISSUE TITLE
Microsoft account log in

### ISSUE THREAD

**Issue by maxsupermanhd** [Tnze/go-mc#106]
I assume Yggdrasil authentication system can not log in with Microsoft credentials since it failed for me, is there a way to authenticate with migrated account?

**Comment by Tnze** [comment]
By following [this guide](https://wiki.vg/Microsoft_Authentication_Scheme) you can get the mc access token which is called `AsTk` in go-mc, the username and the uuid. Then fill these into your `client.Auth`.

The progress is not provided by go-mc. Because it involves calling browser and handling redirect. And the user of go-mc should chose the appropriate implement scheme as needed.

**Comment by maxsupermanhd** [comment]
Yeah, thank you so much, having to implement or use web view for this things is so wrong however people at mineflayer made a very interesting thing, they are showing you some kind of an authorization code to enter on a microsoft website that allow them to proceed a log in. It looks like an easy thing to implement too, no need to even touch client credentials - just prompt to log in via browser.

**Comment by Tnze** [comment]
That could be a good idea. Just like we do half of works and expose the interface of browser things.

However Microsoft is making a great improve of security, the author of third-party launcher never hold the user's password and collect it in the dark - either browser or web view is a black-box for most developer.

**Comment by maxsupermanhd** [comment]
So I spent few (6) hours and designed web-view based authentication scheme, should I open PR or you will just take a look and decide? This authorization hell indeed require window so I created one with https://gtihub.com/webview/webview but it can not close because of issue 588 however it is fully functional and I even joined multiplayer server. Have no idea how this passing to browser works but regardless - it is really complex and there is no shortcuts: Microsoft, XBL, XSTS, MC and profile.

P.S. I don't actually care about it implementing here, I did it inside my other project just for myself. I will invite you to repo for you to check out if you decide.

**Comment by maxsupermanhd** [comment]
Also, it is not a black box, in my implementation I cache Microsoft authorization forever since I got token and refresh token. Sure credentials will be not touched (can be still sniffed with js injection tho) but token is something you can not revoke easily when with credentials you are just changing password or whatever (2fa is for masterminds I suppose at this point (I have it on my Microsoft account and suggest everyone else))

**Comment by Tnze** [comment]
But can you send your token to another device (for example, the IP address is changed) and keep it works good?

**Comment by maxsupermanhd** [comment]
> But can you send your token to another device (for example, the IP address is changed) and keep it works good?

Yes it does.

**Comment by Tnze** [comment]
I'll check it tomorrow.

**Comment by Tnze** [comment]
Can I use BSD library (golang.org/x/oauth2) in MIT project?

**Comment by spbinns** [comment]
> Can I use BSD library (golang.org/x/oauth2) in MIT project?

Yes 

https://softwareengineering.stackexchange.com/questions/278126/is-it-legal-to-include-bsd-licensed-code-within-an-mit-licensed-project

**Comment by maxsupermanhd** [comment]
Also for some reason I was completely blind, it is called device authorization flow and it is very similar to what I have now, just replaces browser with redirect for a pooling of url with code with a bit of a logic. Should I implement it and open PR or you will take it a try by yourself?

**Comment by Tnze** [comment]
I would like to have a try.

**Comment by maxsupermanhd** [comment]
Well, I was impatient https://github.com/maxsupermanhd/go-mc-ms-auth

**Comment by Tnze** [comment]
That's cool. You can link to your lib from my readme so that others can know.

**Comment by emyfops** [comment]
2 years ago I took max's code as a base for a "better" authentication library in my go-mc fork
If you're interested, you can port this in the main project https://github.com/Edouard127/go-mc/tree/master/auth/microsoft

Note that I am no longer interested in coding go-mc
@Tnze

**Comment by maxsupermanhd** [comment]
> "better" authentication library

Please don't use `fmt.Errorf` for constant errors, declare them as exported globals so that code getting the error can check for it with `errors.Is`.

Also, providing paths for credentials store is essential for this kind of code, never thought about people having more than 1 account to use concurrently?

As well as having something better than `fmt.Print` to notify of device flow code, I thought about `chan any` that would do the comms and auth in different routine all together, remember that not all auth is made via terminal.

So far found nothing "better" in your approach compared to mine.

**Comment by emyfops** [comment]
Maybe giving a list of flaws on code I wrote 2 years ago and being more open/constructive would make me want to contribute to the main project

I said that I am **no longer interested** in coding go-mc, Tnze can skip through my code and add whatever he wants

This code was quickly patched together for a simple authentication library that uses existing structs instead of having to cast everything
