### ISSUE TITLE
Use block

### ISSUE THREAD

**Issue by maxsupermanhd** [Tnze/go-mc#107]
How to properly send use block packet? I think I need to use `UseItem` id and then feed it with some data, is there any example how to do so?

**Comment by maxsupermanhd** [comment]
I made this kind of structure but does not seem to work...
```

	c.Conn.WritePacket(pk.Marshal(
		packetid.UseItem,
		pk.VarInt(0), //hand
		pk.VarInt64(((Int64(x) & 0x3FFFFFF) << 38) | ((Int64(z) & 0x3FFFFFF) << 12) | (Int64(y) & 0xFFF);), //position
		pk.VarFloat(0.5), //cursor x
		pk.VarFloat(0.5), //y
		pk.VarFloat(0.5), //z
		pk.VarBool(false), //inside
	))
	```

**Comment by MscBaiMeow** [comment]
I don't know how to use block,but if you just want to send useItem,please read document more carefully.
<https://wiki.vg/Protocol#Use_Item>
Don't attach extra fields.

**Comment by maxsupermanhd** [comment]
No, this use that you linked is different, it just uses held item in the air. I am asking about button press for example...

**Comment by maxsupermanhd** [comment]
Welp, somehow I changed something (I guess just added a bit of a delay) and it works :shrug:. Why? I don't know. Here is final packet:
```
McClient.Conn.WritePacket(pk.Marshal(
  packetid.BlockPlace,
  pk.VarInt(0), //hand
  pk.Position(pk.Position{X: x, Y: y, Z: z}),
  pk.VarInt(4),      //direction
  pk.Float(0.836),   //cursor x
  pk.Float(0.187),   //y
  pk.Float(0.5),     //z
  pk.Boolean(false), //inside
))
```
Actually cursor position matters, server sometimes check for it...
