### ISSUE TITLE
Change protocol version to var

### ISSUE THREAD

**Issue by jolheiser** [Tnze/go-mc#111]
Rather than a `const`, what about making it a `var`?

Reason being it would allow a little flexibility for patch version changes, e.g. right now I cannot join `1.17.1` servers until there is a new version of this library with an incremented protocol number.
The current workaround is to change the code in my module cache, but that's not a great long-term solution.

I would be more than happy to submit a PR for this, or if you have an alternative you'd prefer. :slightly_smiling_face: 

https://github.com/Tnze/go-mc/blob/6500fbeaab50c9fa0e589d0e9e442dde943a4c9d/bot/mcbot.go#L20

I know there are changes between versions, but to my knowledge patch versions usually don't change much.

**Comment by Tnze** [comment]
Packet IDs change a lot.

**Comment by jolheiser** [comment]
Looking further yes, I see packet IDs tend to change a fair amount.

I simply changed the `const` in my module cache. fwiw it was able to log in correctly, but it was a very basic test. :sweat_smile:
