### ISSUE TITLE
Timeout keepalive

### ISSUE THREAD

**Issue by jolheiser** [Tnze/go-mc#114]
Currently the `bot` package times out due to no keepalive packet handling. 

I plan on opening a PR, but am filing an issue to remind myself and also to bring it up in case you had other concerns.

I've fixed it locally with the following

```go
client.Events.AddListener(bot.PacketHandler{Priority: 64, ID: packetid.KeepAliveClientbound, F: keepalive(client)})

...

func keepalive(c *bot.Client) func(packet.Packet) error {
	return func(pk packet.Packet) error {
		var id packet.Long
		if err := pk.Scan(&id); err != nil {
			return err
		}
		return c.Conn.WritePacket(packet.Marshal(
			packetid.KeepAliveServerbound,
			id,
		))
	}
}
```

of course if it's handled internally the code would be _slightly_ different, but this is the idea. Simply return the same ID received by the server.

**Comment by Tnze** [comment]
The `bot/basic` module handles the keepalive.

**Comment by jolheiser** [comment]
> The `bot/basic` module handles the keepalive.

_Should_ it, though? It seems that any client would need to be able to reply to a health check?

**Comment by Tnze** [comment]
That's why it names "basic". Means everyone should need it.

Expect someone tends to writing an huge, powerful, highly customized package to replace all of them, for control everything. So I make it an option.
