### ISSUE TITLE
Example of using pk.Ary handle window click(0x08) packet

### ISSUE THREAD

**Issue by patyhank** [Tnze/go-mc#116]
in 1.17 0x08(Click Window) packet
It's added ``Array of slots`` part
is there any example by using ``pk.Ary`` handle this packet?

wiki.vg: https://wiki.vg/Protocol#Click_Window

**Comment by Tnze** [comment]
In busy, you need both `pk.Ary` and `pk.Tuple`.

**Comment by Tnze** [comment]
There is an example right here: https://github.com/Tnze/go-mc/blob/57b0a6fdc603dc1ce14f7b968bd2bbe315922781/bot/screen/screen.go#L56-L87
