### ISSUE TITLE
How do I login into a actual Minecraft account?

### ISSUE THREAD

**Issue by zyme-xd** [Tnze/go-mc#119]
Sorry for leaving so many issues, but I couldn't figure it out

**Comment by jolheiser** [comment]
[This comment](https://github.com/Tnze/go-mc/issues/26#issuecomment-534596978) describes how to do it. 

Perhaps it could be added to the examples or README, though.

**Comment by zyme-xd** [comment]
Yeah it probably should be added to the readme or an example

**Comment by Tnze** [comment]
You really should read the document roughly.
https://pkg.go.dev/github.com/Tnze/go-mc@v1.17.0/bot#example-Client.JoinServer-Online

**Comment by Tnze** [comment]
And for the Microsoft Account, check #106.
