### ISSUE TITLE
Incorret Yggdrasil  URI

### ISSUE THREAD

**Issue by claudio4** [Tnze/go-mc#12]
Hello

The Yggdrasil package tries to login against https://authserver.mojang.com/yggdrasil 
 ([yggdrasil/authenticate.go:46](https://github.com/Tnze/go-mc/blob/master/yggdrasil/authenticate.go#L46)) but that is not a valid endpoint in the Mojang server, causing the login fails with the message {"error":"Not Found","errorMessage":"The server has not found anything matching the request URI"}, instead of this URI the package should use https://authserver.mojang.com/authenticate as [wiki.vg states](https://wiki.vg/Authentication#Endpoint)

**Comment by Tnze** [comment]
I just repaired this locally.
![)(K_(V_}F2TRHX8S0 L ~{Y](https://user-images.githubusercontent.com/19628575/62713582-8e96fd80-ba2f-11e9-9473-6e4139235138.jpg)

**Comment by claudio4** [comment]
Oh

**Comment by Tnze** [comment]
The Yggdrasil package is being redesigned。😏

**Comment by claudio4** [comment]
Nice, thank you
