### ISSUE TITLE
nbt.Marshal and map[string]interface{}

### ISSUE THREAD

**Issue by RuscalWorld** [Tnze/go-mc#121]
I'm trying to make a tool that allows to edit files stored in NBT format. So, I don't know structures of files that will be used with my tool. My program loads file to a variable with type `map[string]interface{}`, changes some values there and then saves this map to another file. But it saves all values with `Compound` type even if these values had another types.

There are several variables:
```go
var (
	CurrentData map[string]interface{}
	InputFilePath  = ""
	OutputFilePath = ""
)
```

Loading file looks like this:
```go
func LoadData() error {
	file, err := os.Open(InputFilePath)
	if err != nil {
		return err
	}

	defer file.Close()

	reader, err := gzip.NewReader(file)
	if err != nil {
		return err
	}

	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return err
	}

	return nbt.Unmarshal(data, &CurrentData)
}
```

And saving:
```go
func SaveData() error {
	data, err := nbt.Marshal(CurrentData)
	if err != nil {
		return err
	}

	var buffer bytes.Buffer
	writer := gzip.NewWriter(&buffer)
	_, err = writer.Write(data)
	if err != nil {
		return err
	}

	writer.Flush()
	writer.Close()

	err = ioutil.WriteFile(OutputFilePath, buffer.Bytes(), 0644)
	return err
}
```

File before edit:
![image](https://user-images.githubusercontent.com/60034902/130777641-ab7e4bf1-ac54-4db1-a520-7945bed5ea92.png)

After edit:
![image](https://user-images.githubusercontent.com/60034902/130777889-2c13c954-113f-498e-8517-83c267d98070.png)

Is this a bug of the library or I'm doing something wrong?

**Comment by Tnze** [comment]
The type info is missing in map. This can not be "repaired".

**Comment by RuscalWorld** [comment]
> The type info is missing in map. This can not be "repaired".
But I have another feature in my tool that allows to see what happens in `CurrentData`. If I add this magic function before `nbt.Marshal`:
```go
	PrintTree(context)
	data, err := nbt.Marshal(CurrentData)
	if err != nil {
		return err
	}
```

... it will print all this data with correct types:
```
├── Data (Compound)
│   ├── BorderSizeLerpTime: 0 (Long)
│   ├── DragonFight (Compound)
│   │   ├── NeedsStateScanning: 1 (Byte)
│   │   ├── Gateways (List)
│   │   │   ├── 18: 3 (Int)
│   │   │   ├── 9: 6 (Int)
│   │   │   ├── 11: 8 (Int)
│   │   │   ├── 16: 0 (Int)
│   │   │   ├── 14: 11 (Int)
│   │   │   ├── 4: 18 (Int)
│   │   │   ├── 6: 17 (Int)
│   │   │   ├── 10: 7 (Int)
│   │   │   ├── 19: 19 (Int)
│   │   │   ├── 1: 1 (Int)
│   │   │   ├── 2: 9 (Int)
│   │   │   ├── 17: 12 (Int)
│   │   │   ├── 7: 4 (Int)
│   │   │   ├── 8: 10 (Int)
│   │   │   ├── 12: 2 (Int)
│   │   │   ├── 13: 13 (Int)
│   │   │   ├── 15: 5 (Int)
│   │   │   ├── 0: 15 (Int)
│   │   │   ├── 3: 14 (Int)
│   │   │   └── 5: 16 (Int)
│   │   ├── DragonKilled: 1 (Byte)
│   │   └── PreviouslyKilled: 1 (Byte)
│   ├── GameRules (Compound)
│   │   ├── logAdminCommands: "true" (String)
│   │   ├── sendCommandFeedback: "true" (String)
│   │   ├── announceAdvancements: "true" (String)
│   │   ├── naturalRegeneration: "true" (String)
│   │   ├── fallDamage: "true" (String)
│   │   ├── doEntityDrops: "true" (String)
│   │   ├── doLimitedCrafting: "false" (String)
│   │   ├── fireDamage: "true" (String)
│   │   ├── universalAnger: "false" (String)
│   │   ├── playersSleepingPercentage: "100" (String)
...
```

It's because `interface{}` does not "erase" type. And you can "restore" original type with, for example, type assertion.

**Comment by Tnze** [comment]
May be this is a bug

**Comment by RuscalWorld** [comment]
I've decided to try out new version of go-mc in my program, and it looks like it does not work again :)

When I call `nbt.Marshal`, it panics [here](https://github.com/Tnze/go-mc/blob/master/nbt/encode.go#L87):
```
panic: reflect: call of reflect.Value.Int on interface Value
```
