### ISSUE TITLE
On disconnect, my program exits

### ISSUE THREAD

**Issue by zyme-xd** [Tnze/go-mc#123]
Is this because of the library or my program, I have a fmt.Scanln() in my code waiting for input before exiting but the disconnect makes my code completely ignore that.

**Comment by Tnze** [comment]
Make sure you add this line in the end of your main function. 

I guess this is because OnDisconnect is only executed when the server proactively close the connection.

**Comment by zyme-xd** [comment]
I will test this when I get home from school, thank you

**Comment by zyme-xd** [comment]
Sadly, this fix didn't work. You can take a look at my code on [this](https://github.com/zyme-xd/kaychecker) repo.
Maybe I did something wrong with it but I think its fine

**Comment by zyme-xd** [comment]
I fixed it, it was because i had `log.Fatal`, and that caused the program to exit
