### ISSUE TITLE
Request to make handleEncryptionRequest public

### ISSUE THREAD

**Issue by layou233** [Tnze/go-mc#125]
https://github.com/Tnze/go-mc/blob/7b5e289786e9dacd2fd1d374702efa1cf734cb42/bot/login.go#L28

这一个方法内部的实现非常完善，我想请求把这个方法变为public，也就是把首字母大写，方便在自己程序中调用。  
因为对于有些场景不适合调用内建JoinServer的（比如需要使用特定版本号登录，我看过pinned issue并理解您不允许自定义兼容多版本的原因，但是我只是需要更改一个版本号），我需要另外实现一套登录，但是对于处理Encryption Request的方法并不需要更改，然而库中已经实现的东西我还需要一模一样复制一遍，感觉很浪费啊，尴尬，强迫症有点发作了XD  
啊，另外我也是高中生，祝你考试顺利！

**Comment by Tnze** [comment]
确实应该允许自定义登录过程，方式应当是把握手加密的部分也模块化。这样也能顺便提供诸如自定义Login Plugin Request/Response的功能
