### ISSUE TITLE
Discord server?

### ISSUE THREAD

**Issue by comblock** [Tnze/go-mc#129]
It would be cool if there was a discord server for the project, so people could ask for help or share the projects they're working on.

**Comment by Tnze** [comment]
I will be happy if there are enough users participating this project to establish a community. Anyway, it's quite troublesome to visit Discord for me.

**Comment by comblock** [comment]
> I will be happy if there are enough users participating this project to establish a community. Anyway, it's quite troublesome to visit Discord for me.

The project allready has 396 github stars and 70 forks so I think there would be enough people to at least start a (very) small community.

**Comment by maxsupermanhd** [comment]
I agree on this issue, Discord server would be really cool to have

**Comment by comblock** [comment]
Even if it had only 10 people in it, it would still be incredibly fun and useful.

**Comment by Tnze** [comment]
https://discord.gg/A4qh8BT8Ue

**Comment by Tnze** [comment]
\[Webhook test\]
