### ISSUE TITLE
Minecraft 1.18 chunk format

### ISSUE THREAD

**Issue by jeremistadler** [Tnze/go-mc#136]
The genmap example only generates empty png files, I think this might be because of changes in the chunk format in 1.18?

Specifficaly, the Column.Load function does not change the Column struct except setting the DataVersion to 2865.

Tested with 1.17.1 and master 19481ab

**Comment by Tnze** [comment]
The Chunk represents work in progress

**Comment by katelinlis** [comment]
dimension.go:76

stateIDs not init 
stateIDs = make(map[string]uint32)

**Comment by Tnze** [comment]
fixed in my local code

**Comment by pkramme** [comment]
Is there anything I can do to help here? I am very interested in 1.18 chunk support.

**Comment by Tnze** [comment]
Join our discord and we are talking about this

**Comment by Tnze** [comment]
duplicate: #110
