### ISSUE TITLE
How to easily extrat text and username from chat.Message

### ISSUE THREAD

**Issue by claudio4** [Tnze/go-mc#14]
Hello

There is a way to directly get the content of the message and author name, each one in a variable from a chat.Message?

**Comment by Tnze** [comment]
```go
cs := msg.ClearString()
var name, content string
fmt.Sscanf(cs, "<%s>", &name)
content = cs[len(name)+3:]
```
I think the best way is ... Just deal with the string

**Comment by Tnze** [comment]
For notchian server, they use a translating chat "chat.type.text". 
Looks like 
```go
chat.Message{
      Translate:"chat.type.text",
      With: []json.RawMessage{
            json.RawMessage{"author"}, 
            json.RawMessage{"content"},
      }
}
```
But Bukkit servers only send a string.

**Comment by claudio4** [comment]
The Sscanf way doesn't work, at least for me, the name stays blank and content has `EXTRA string=Claudio4, string=t)`
The RawMessage seems to work pretty well, it's a shame that it doesn't work on Bukkit

**Comment by Tnze** [comment]
```go
package main

import (
	"fmt"
	"strings"
)

func main() {
	msg     := "<Tnze with blank> Hello?? ? ?"
	
	name    := msg[1:strings.IndexByte(msg, '>')]
	content := msg[len(name)+3:]
	
	fmt.Println("name:", name)
	fmt.Println("cont:", content)
}
```

**Comment by claudio4** [comment]
The problem is that ClearString doesn't produce a string like that
it's more like this `%!(EXTRA string=Tnze with blank, string=Hello?? ? ?)`

**Comment by Tnze** [comment]
I got it, your problem is that the translation dictionary is not loaded. You need import one of data/lang package.
```go
import _ "github.com/Tnze/go-mc/data/lang/en-us"
```
