### ISSUE TITLE
Inconsistent with wiki.vg

### ISSUE THREAD

**Issue by layou233** [Tnze/go-mc#143]
我正在计划按照 #125 提出时所想，在`bot`包下面再建一个`login`包，用于封装一些登录过程并且提供API。  
但是我发现原`bot`的Mojang API `JoinServer`实现与wiki.vg上所提并不相符。  
https://wiki.vg/Protocol_Encryption#Authentication  
`selectedProfile`在wiki.vg上描述应为

> player's uuid without dashes

但实际上，`bot`包中把此selectedProfile当做yggdrasil中authenticate的同名对象，事实上并不是一码事。  
https://github.com/Tnze/go-mc/blob/c724909cd71137ae3ff490b034a20d7a3c80e694/bot/login.go#L133  
令我神奇的是这么做好像在之前的程序中未发现bug，这个是本来就可以这么设计吗？

**Comment by Tnze** [comment]
yggdrasil中authenticate的UUID本身就是without dashes的一个字符串，所以可以直接用。

虽说如果传递uuid.UUID从设计上来讲确实会好些，但是考虑到兼容性暂时还是保留了原本的API

**Comment by layou233** [comment]
> 

我的意思是，本库的代码为
```go
requestPacket, err := json.Marshal(
		request{
			AccessToken: auth.AsTk,
			SelectedProfile: profile{
				ID:   auth.UUID,
				Name: auth.Name,
			},
			ServerID: digest,
		},
	)
```
但实际上，按照wiki.vg来，他应该是这样
```go
requestPacket, err := json.Marshal(
		request{
			AccessToken: auth.AsTk,
			SelectedProfile: auth.UUID,
			ServerID: digest,
		},
	)
```

**Comment by Tnze** [comment]
wiki.vg changed

**Comment by layou233** [comment]
https://wiki.vg/index.php?title=Protocol_Encryption&diff=next&oldid=8391  
确实发生了更改，是否应该跟从wiji.vg的修改？

**Comment by Tnze** [comment]
随便写，能跑就行

**Comment by patyhank** [comment]
跑得起來比較重要#
