### ISSUE TITLE
NBT deserializing [help]

### ISSUE THREAD

**Issue by wojtess** [Tnze/go-mc#146]
How to deserialize NBT from packet?

**Comment by comblock** [comment]
You can use the go-mc/nbt package for this, there are examples on https://pkg.go.dev

**Comment by Tnze** [comment]
Did you means 'pk.NBT()' ?

**Comment by wojtess** [comment]
`pk.NBT()` is used for marshmal, i want to unmarshmal NBT from join game packet
(https://wiki.vg/Protocol#Join_Game)

**Comment by Tnze** [comment]
You are wrong

**Comment by Tnze** [comment]
pk.NBT is not only for marshals
