### ISSUE TITLE
How to Open Chest

### ISSUE THREAD

**Issue by qiufeng6407** [Tnze/go-mc#147]
Yes! You can do it.
What you need is make sure the target chest is in ranged. Then `UseBlock` it. The server will send you a [`Open Window`](https://wiki.vg/Protocol#Open_Window) packet, which you must handle by setting `c.Events`  a event handler to receive.

Do the same thing with the crafting table if you want to craft them.

_Originally posted by @Tnze in https://github.com/Tnze/go-mc/issues/52#issuecomment-618223928_

**Comment by qiufeng6407** [comment]
请问一下再 1.18.1中，如何打开箱子和工作台呢，上文中提到的`UseBlock` 是用哪个packet实现的呢

**Comment by Tnze** [comment]
试试Player_Block_Placement？
我不太确定，以前是有UseBlock的。。

**Comment by qiufeng6407** [comment]
试过了，不太行，我在服务端装了`ProtocolLib`抓客户端的包，看发的是`Player_Block_Placement`和`Animation`，但是我这边同样的发却没有效果，不知道漏了什么步骤

**Comment by Tnze** [comment]
可能你需要把视角转过去对着箱子

**Comment by qiufeng6407** [comment]
嗯，都转过去了，我用正常的客户端抓的包，然后把视角，鼠标的点，Yaw And Pitch，都设置的一模一样，都不行 T.T

**Comment by qiufeng6407** [comment]
没事了，是 `Player_Block_Placement`，是我自己的问题，出生点没有OP权限。。
