### ISSUE TITLE
Zlib: Incorrect Header Check

### ISSUE THREAD

**Issue by bendgk** [Tnze/go-mc#149]
### What is wrong
When using `Conn.setThreshold(256)` and sending packets larger than the compression threshold the client will error out.  Most of the time the error is along the lines of  `ZLib Incorrect Header` however other times the error will be `VarInt too big` or various other decoding issues

### What I think the solution is
use [deflate](https://pkg.go.dev/compress/flate) instead of [zlib](https://pkg.go.dev/compress/zlib)
I believe Minecraft uses RFC 1951 for packet compression (not sure as I can't find much info on this topic)

**Comment by Tnze** [comment]
How often did this bug occur?

**Comment by Tnze** [comment]
According to my experience, as for now, my `net.Conn` works just fine.

As your problem, I guess, did you use the `conn.Read()` directly instead of `conn.ReadPacket()`? The two errors you mentioned seem to be happened only when the previous one packet doesn't read correctly or completely.

**Comment by maxsupermanhd** [comment]
Library works perfectly fine with compressed chunk data

**Comment by bendgk** [comment]
> How often did this bug occur?
> 
> Your go-mc version?
> Minecraft version?

go-mc tag 1.17.1
mc version 1.17.1

issue occurs every time I join my server and chunk data is sent (ClientBound)

I am using `Conn.ReadPacket` to consume packets from the connection so I do not believe that is the issue.  

Maybe I didn't articulate this well enough before, but the error message occurs on the client, the server seems to operate fine and no errors show up, leading me to believe its some issue with how the packer is being Packed with Compression.

When compression is disabled client and server behave as expected with no issues and chunk data loads perfectly fine.

Thanks for all the support, great library btw!

**Comment by bendgk** [comment]
> Library works perfectly fine with compressed chunk data

When you mention it works fine with compressed data, are you just running tests, or are you actually sending the packets a vanilla client?

**Comment by Tnze** [comment]
We are talking about the latest version of go-mc. You could try `go get github.com/Tnze/go-mc@master`.

Outdated version do have bug and you shouldn't use them.

**Comment by Tnze** [comment]
> > Library works perfectly fine with compressed chunk data
> 
> @maxsupermanhd 
> 
> When you mention it works fine with compressed chunk data, are you just running tests, or are you actually sending the packets to a vanilla client?

https://github.com/go-mc/pernod

This program work which proof that the compression code is good.

**Comment by maxsupermanhd** [comment]
> > Library works perfectly fine with compressed chunk data
> 
> @maxsupermanhd 
> 
> When you mention it works fine with compressed chunk data, are you just running tests, or are you actually sending the packets to a vanilla client?

Actually sending packets
