### ISSUE TITLE
could not import github.com/Tnze/go-mc/net (no required module provides package "github.com/Tnze/go-mc/net")compilerBrokenImport

### ISSUE THREAD

**Issue by ServerSideProject** [Tnze/go-mc#150]
![image](https://user-images.githubusercontent.com/90555583/155199845-48732be0-669d-432d-9115-ec8540b672b5.png)
![image](https://user-images.githubusercontent.com/90555583/155199877-245c60bc-b07e-408f-b3ff-594447487518.png)
![image](https://user-images.githubusercontent.com/90555583/155199908-7e4f81e7-cf2b-4bf6-bf6a-e4bdc7d983f8.png)
![image](https://user-images.githubusercontent.com/90555583/155199928-9a791b17-78cb-401b-a743-2038bbac42f1.png)

Help xd)

I do not understand how to add a package, I have been suffering for a week

**Comment by comblock** [comment]
You should look into go modules, do `go mod init (module name)` and then `go get github.com/tnze/go-mc@master` to add the package
