### ISSUE TITLE
Get inventory not working

### ISSUE THREAD

**Issue by almc624** [Tnze/go-mc#17]
Anyone having issues trying to fetch the inventory?

I'm trying to check the hotbar and I get this:
```
2019/08/10 16:57:16 minecraft:air, 0, 0, false
2019/08/10 16:57:16 minecraft:air, 0, 0, false
2019/08/10 16:57:16 minecraft:air, 0, 0, false
2019/08/10 16:57:16 minecraft:air, 0, 0, false
2019/08/10 16:57:16 minecraft:air, 0, 0, false
2019/08/10 16:57:16 minecraft:air, 0, 0, false
2019/08/10 16:57:16 minecraft:air, 0, 0, false
2019/08/10 16:57:16 minecraft:air, 0, 0, false
2019/08/10 16:57:16 minecraft:air, 0, 0, false
```

Code:
```
func printHotBar() {
	hotbar := c.HotBar()
	for _, slot := range hotbar {
		log.Println(fmt.Sprintf("%v, %v, %v, %v", slot, slot.Count, slot.ItemID, slot.Present))
	}
}
```

Tested on multiple different servers, same result.

The bar is definitely not empty, as the auto fishing works.

**Comment by Tnze** [comment]
You should use the event of WindowsItem instead. I will remove these method. 
Because it always error when joining other server than use a fix size Inventory.

**Comment by Tnze** [comment]
WindowsID: 0 is the player's Inventory

**Comment by Tnze** [comment]
The outdate methods were removed.
