### ISSUE TITLE
Chat message Append method does not work

### ISSUE THREAD

**Issue by maxsupermanhd** [Tnze/go-mc#170]
Code below should output "Hello world!" in Text field but it does not. It is not even populating Extra array with extra text.
```
msg := chat.Text("Hello ")
msg.Append(chat.Text("world!"))
m, _ := json.MarshalIndent(msg, "", "    ")
fmt.Println(m)
```

**Comment by Tnze** [comment]
```go
msg := chat.Text("Hello ").
           Append(chat.Text("world!"))
```

**Comment by maxsupermanhd** [comment]
Solved by just appending to Extra array, kinda feeling like potato now considering that I looked at Append sources multiple times...

**Comment by Tnze** [comment]
Sorry for no written documents because of my lazy. Let's make it up
