### ISSUE TITLE
nbt.Marshal does not support Int?

### ISSUE THREAD

**Issue by maxsupermanhd** [Tnze/go-mc#173]
I am trying to marshal `map[string]interface{}` to nbt structure to represent block entity but I get error `unsupported value <int Value>`.
Is there a good way to append data to compound tag? What is most efficient way of assembling "default" (empty) block entity nbt message?
Playground: https://go.dev/play/p/eQvbqWc1jNR

**Comment by Tnze** [comment]
you must use one of int32 or int64
