### ISSUE TITLE
nbt.Unmarshal (nbt.getTypeInfo) parse extra fields to fallback field

### ISSUE THREAD

**Issue by maxsupermanhd** [Tnze/go-mc#178]
In JSON deserialization it is allowed to specify `json:"-"` to have a field with "remaining" data that did not found way to the defined structure. Here (looking on `getTypeInfo`) it seems like "-" is treated same as private fields.

**Comment by Tnze** [comment]
nbt lib acts as the same way as json. so what's your problem

**Comment by Tnze** [comment]
You should write an example and tell me what's the output and what's the output you expect it do.

**Comment by maxsupermanhd** [comment]
I am currently making a blockEntity parser/repacker for level.Chunk and save.Chunk and I have troubles storing uncommon data about block entities, made structure to hold common data but extra is not populating...

https://go.dev/play/p/xyh7kOVHyOV

**Comment by Tnze** [comment]
show me how do you do when using json  "remaining" data

**Comment by maxsupermanhd** [comment]
Well, actually, json does not have it but we can have it, here is how I solved it: https://github.com/maxsupermanhd/go-mc/commit/239ddff1aa5cd0a256d24681eb8e8368ee672b8c

**Comment by maxsupermanhd** [comment]
marking as suggestion prob good idea
