### ISSUE TITLE
No access to palette containers's raw data (only through marshling it to buffer)

### ISSUE THREAD

**Issue by maxsupermanhd** [Tnze/go-mc#183]
I would like to have palette containers data to be exported because it is easier to manipulate it this way

**Comment by Tnze** [comment]
But we can't offer a unified port for all possible palette implements.
Is there another use case of `palette.export()` method?

**Comment by maxsupermanhd** [comment]
Yes, as I described earlier it would be much easier to check that palette contains something in header rather than loop through data. For example I want to check for presents of chests in a section - right now only way to do that would be to check all 4096 positions but could be optimized to only check that chest blockstates present in states palette.

**Comment by maxsupermanhd** [comment]
Not sure about data but palette must be accessible.

**Comment by Tnze** [comment]
That make sense. Should we just export the palette or offer a `Exist() bool` method? And should we also export the BitStorage data field?

**Comment by maxsupermanhd** [comment]
Just export palette, why dictate what someone would want to do with it be it checking existence or something else? If someone wants to perform operation on palette it is his job to do it, library's job is to provide it. Best would be to have both so we don't multiply same exist routine and have full palette access.
Also good thing to have is ability to override palette, one of applications would be to mass block change like from white concrete to glass, however this is already getting overly advance, maybe just providing bunch of options will be good. I would just made a getter/setter for raw data and palette, if people know what they are doing lack of those abilities just getting in the way.
BitStorage might be useful but I don't see applications outside of converting paletted data from one form to another, if this will be done properly by the library (khm #164) it should not be needed.

**Comment by Tnze** [comment]
The palette implement is complicated. Should we hide the specific palette implementation (singlevalue, liner, hash or global) and just export a `[]int` like current `export()` function, or expose the palette interface and all implementations struct?
