### ISSUE TITLE
server.LevelInfo should be replaced with getters from dimension provider

### ISSUE THREAD

**Issue by maxsupermanhd** [Tnze/go-mc#189]
What if I have multiple dimensions?

**Comment by Tnze** [comment]
Do you means `server.SimpleDim.Info()`?
Yes, but we need a dimension manager first. I haven't figured out what to do when players transfer between dimensions

**Comment by Tnze** [comment]
This issue will be close because it points out the problem of the unfinished part of the code, and the problem will surely be fixed in the future.
