### ISSUE TITLE
 机器人可以移动（谷歌翻译) :D// Is there a method that allows bots to move?

### ISSUE THREAD

**Issue by win32prog** [Tnze/go-mc#19]
I'm looking for a method that can make my bot move blocks. Is their a existing method in the project that I missed?

**Comment by win32prog** [comment]
So I found this in  /bot/world/motion.go
``
// // SetPosition method move your character around.
// // Server will ignore this if changes too much.
// func (g *Client) SetPosition(x, y, z float64, onGround bool) {
// 	g.motion <- func() {
// 		g.player.X, g.player.Y, g.player.Z = x, y, z
// 		g.player.OnGround = onGround
// 		sendPlayerPositionPacket(g) //向服务器更新位置
// 	}
// }
``
wondering if that has anything to do with this

**Comment by win32prog** [comment]
I also found the function "handlePlayerPosistionAndLookPacket" in bot/ingame.go probs should've looked harder

**Comment by Tnze** [comment]
用中文还是英文？_(:з」∠)_

**Comment by win32prog** [comment]
English pls

**Comment by Tnze** [comment]
Okay, but my English is not very good.🙃

I had try to add movement method in the old version of go-mc(github.com/Tnze/gomcbot). But I don't think that's good enough.

**Comment by win32prog** [comment]
I see, I'm gonna arround that repo and see if I can find the movement method. Hopefully I can use it. Thanks for reply!

**Comment by Tnze** [comment]
https://github.com/Tnze/go-mc/blob/af335efc18df34096393543ddfd0aaa809e26e43/bot/motion.go#L193
I add this for a easy way to send custom packet.
