### ISSUE TITLE
[Dim] Chunk Ticking & Player Operations

### ISSUE THREAD

**Issue by Tnze** [Tnze/go-mc#193]
Current server framework doesn't allow players destroy or place blocks. The operations are shown in client but not handled in the server side. All changes will not be kept.

Chunks also doesn't ticking. The fire should spread, the sand should fall, the leaves of cut trees should wither... These functions should be realized by the server periodically processing the game world

**Comment by Tnze** [comment]
When server processing chunks, It should decide which blocks should be processed. It is to be noted that there should be an intermediate state between "loaded" and "active".

This requires good compatibility with #192 .

**Comment by maxsupermanhd** [comment]
It should be optional because sometimes you don't want to give players ability to modify anything.
