### ISSUE TITLE
Heightmaps...

### ISSUE THREAD

**Issue by maxsupermanhd** [Tnze/go-mc#194]
As of [5f3f66e](https://github.com/Tnze/go-mc/commit/5f3f66e9cfcb9ebaa610504c8516c2a09f5ecf42) level.ChunkFromSave does not check that palettes actually valid length or even present and level.ChunkToSave does not store motion blocking heightmap at all.

Idea is to make such heightmap based on already available sections if one is not present due to conversion from level to save.

**Comment by Tnze** [comment]
Shall already be fixed.

> level.ChunkToSave does not store motion blocking heightmap at all.

At least confirmed this is fixed.
