### ISSUE TITLE
getting: auth fail and recv packet for Login fail errors

### ISSUE THREAD

**Issue by Succ3s** [Tnze/go-mc#2]
Hello, I'm trying to run `.cmd/daze/daze.go` but I'm getting this errors:
`login fail: auth fail: {"error":"IllegalArgumentException","errorMessage":"Access Token can not be null or empty."}`
and 
`bot: recv packet for Login fail: read len of packet fail: EOF`

**Comment by DeepRobin** [comment]
I get the error too. My code: https://hastebin.com/exuqeyulob.go

**Comment by DeepRobin** [comment]
I think the error is here https://github.com/Tnze/go-mc/blob/0d436609ce8bac2393c2faa485e4d8dd625d627b/net/packet/packet.go#L67 

@Tnze You can try only to return if error != EOF

**Comment by Tnze** [comment]
It looks like you are using an offline client but trying to join an online-mode server.

**Comment by Tnze** [comment]
I found that the authenticating fail is not reported at https://github.com/Tnze/go-mc/blob/4dee74b11957ed5e0eaab5009dd91240cae2a1ec/bot/mcbot.go#L133
It causes that when login fail, program is not return but continuing receive packet from server. At this time the server disconnect and client get EOF.

**Comment by Tnze** [comment]
Thanks for this issue. The problem of inaccurate error messages has been fixed. Reopen for any problem.

**Comment by DeepRobin** [comment]
It doen't work :/
My source: https://hasteb.in/evixacag.go
Error: `bot: encryption fail: login fail: auth fail: {"error":"ForbiddenOperationException","errorMessage":"Invalid token"}`

**Comment by Succ3s** [comment]
I'm getting `bot: encryption fail: login fail: auth fail: {"error":"IllegalArgumentException","errorMessage":"Access Token can not be null or empty."}`


I startup my "server" by clicking "open to LAN", is it the right way?

**Comment by Succ3s** [comment]
@Tnze I can't re-open

**Comment by Tnze** [comment]
I'm sorry about that. This is my mistake. You should set client.AsTk = response.AccessToken , not the SelectedProfile.ID

**Comment by Tnze** [comment]
https://github.com/Tnze/go-mc/commit/b396e2f9d5d491c1759a86a6dd622b7f58993c72#diff-ec9244da44a33b6c87eeb6126f2dbf49

**Comment by Tnze** [comment]
@Succ3s Does it work?

**Comment by Succ3s** [comment]
still getting `bot: encryption fail: login fail: auth fail: {"error":"IllegalArgumentException","errorMessage":"Access Token can not be null or empty."}` :(

**Comment by Succ3s** [comment]
I'm trying just with an offline server, I will try with an online

**Comment by Succ3s** [comment]
@Tnze I think I found the error, I will do some tests to see

at least the bot joined :D

**Comment by Succ3s** [comment]
at the end of `loginAuth` function you're checking if `resp.Status != "204 No Content"`, i changed the "!=" to "==" and it worked

**Comment by Tnze** [comment]
Could you print your `resp.Status`? I don't understand.

**Comment by Tnze** [comment]
It should be `204 No Content` when success.

**Comment by Tnze** [comment]
you can check if AsTk is empty at `loginAuth`.
The error message is returned from Mojang:`{"error":"IllegalArgumentException","errorMessage":"Access Token can not be null or empty."}`. It seems like your AsTk is empty

**Comment by Succ3s** [comment]
when you try to join an offline server you don't need to authenticate but the lib try to authenticate so it return `404 not found`

**Comment by Tnze** [comment]
Nope, offline server will not send `Encryption Request` packet. So it doesn't try to authenticate.
https://github.com/Tnze/go-mc/blob/837bb0b213c124000b8b6ad9d4fcb5bfeac9fb96/bot/mcbot.go#L136
I tested it.

**Comment by Tnze** [comment]
It shouldn't get `404` anyway. Even if request is null, mojang return this
```json
{
    "error": "IllegalArgumentException",
    "errorMessage": "token is marked @NonNull but is null"
}
```
May be you need `go get -u github.com/Tnze/go-mc/bot` and try again?

**Comment by Tnze** [comment]
or....Is it possible that the network environment has different effects?

**Comment by Succ3s** [comment]
case 0x01 calls handleEncryptionRequest which calls loginAuth

**Comment by Tnze** [comment]
But offline server doesn't send 0x01 packet.

**Comment by Tnze** [comment]
offline game will not encrypt the connection.

**Comment by Tnze** [comment]
When I join a online-mode server by offline-mode client, I got `
bot: encryption fail: login fail: auth fail: {"error":"IllegalArgumentException","errorMessage":"Access Token can not be null or empty."}`. 
That's because of online-server is trying to let client login, but offline-client hasn't a AccessToken.

**Comment by Succ3s** [comment]
by clicking `open to LAN` in opening an offline server, right?

**Comment by DeepRobin** [comment]
It is working now?

**Comment by Tnze** [comment]
That's not right. You should download a server.jar from minecraft.net. See https://minecraft.gamepedia.com/Server

**Comment by Succ3s** [comment]
oh sorry, my bad :(
