### ISSUE TITLE
Handle packet error 0x1A (run daze)

### ISSUE THREAD

**Issue by ThunderPanda** [Tnze/go-mc#20]
I get the following error when trying to run "daze"

xxxxxxxxxxxx Login success
xxxxxxxxxxxx handle packet 0x1A error: invalid character '\n' in string literal

What am I supposed to do?

**Comment by MscBaiMeow** [comment]
Please paste the time of the logs

**Comment by ThunderPanda** [comment]
2019/08/29 18:53:14 Login success
2019/08/29 18:53:15 handle packet 0x1A error: invalid character 'ßn' in string literal
exit status 1

Im using Version Minecraft version 1.14.4 und the latest go-mc version.

**Comment by MscBaiMeow** [comment]
It works well on my computer.Can you offer more information?

**Comment by ThunderPanda** [comment]
I got it fixed. I had to change the port, since the server I connected to was using a different one than 25565
