### ISSUE TITLE
Unable to parse chat messages received from normal users.

### ISSUE THREAD

**Issue by 6uf** [Tnze/go-mc#201]
**Describe the bug**

`handle packet 0xF error: bot/basic: json: cannot unmarshal array into Go struct field jsonMsg.extra of type chat.jsonMsg`
I get this error when ever a normal user sends a chat message in the server.

**To Reproduce**
1. Go Version: 1.18
2. GoMC Version: github.com/Tnze/go-mc v1.18.3-0.20220528143224-a67d01b81f0d
3. Code:

```go
if err := C.HandleGame(); err != nil {
	fmt.Println(err)
}
```

**Expected output**

```
a normal chat message, like Welcome User.
```

**Current output**

```json
{
   "extra": [
     {...},
     {...},
     "",
     {...}
   ]
}
```

the issue here is the returned packet byte is adding a empty "" inside of the "extra" array, this is causing it to fail parsing to a go struct etc, no idea how i can fix this currently. i have tried removing the string from the extras list but that gives me unexpected EOF when doing the normal ReadFrom in the Scan function. 

![Img](https://media.discordapp.net/attachments/118456055842734083/979862301249261578/unknown.png)

**Additional context**

Seems to be a parsing issue, idk how u would go about to fix this since i dont know the backend as well, gl.

**Comment by maxsupermanhd** [comment]
Somewhere where it is being parsed it has to be stripped from that sort of things. I think such a message is technically is invalid but bet in client there is fallbacks on initialization of classes or something similar. I am aware that a special parser will have to be implemented to handle such garbage chat messages.

**Comment by 6uf** [comment]
i was able to remove the empty string and replace the old json with the new one but i get unexpected EOF errors, no idea.

i may try to make my own library for this stuff ill take this into account while coding it.

**Comment by Tnze** [comment]
I think that's a valid chat json. Can you receive that json message as `pk.String` and parse here? It should be added to the unit test.

**Comment by Tnze** [comment]
Test case: `{"extra":[{"text":"aaaa"},"bbbb","",{"text":"cccc"}]}`
Output: `aaaabbbbcccc`.

So I think I've handle that correctly here.
https://github.com/Tnze/go-mc/blob/a67d01b81f0d6b35d782089d4207e6920619c804/chat/message.go#L103-L115

**Comment by Tnze** [comment]
##### Example test code

```go
func ExampleMessage_ReadFrom() {
	var p = pk.Marshal(
		packetid.ClientboundChat,
		pk.String(`{"extra":[{"color":"white","text":"Tnze"},"",{"text":"Tnze"}]}`),
		pk.Byte(0),
		pk.UUID{},
	)

	var msg chat.Message
	if err := p.Scan(&msg); err != nil {
		panic(err)
	}
	fmt.Println(msg.ClearString())
	// Output: TnzeTnze
}
```

##### The `go test` output

```
=== RUN   ExampleMessage_ReadFrom
--- PASS: ExampleMessage_ReadFrom (0.00s)
PASS
```

**Comment by Tnze** [comment]
According to the error message: `json: cannot unmarshal array into Go struct field jsonMsg.extra of type chat.jsonMsg`

You are probably using a version of go-mc before https://github.com/Tnze/go-mc/commit/67806abcdb744eebeca5f3a1d8d0107a2d5cbf46

**Comment by 6uf** [comment]
i updated to the very latest version of go-mc, the error originates from the Scan function. 

https://github.com/Tnze/go-mc/blob/master/net/packet/packet.go

it returns the error while trying to append to the chat.Message.. idk what to do. lol

**Comment by 6uf** [comment]
![image](https://user-images.githubusercontent.com/86650306/170889575-2dbfebb3-b43d-41f7-b226-c3b363d9ff95.png)
The issue i assume is causing it is the emojis of the json itself, also the scan command i dont see anything there for unmarshaling etc, idk what the issue could be.. ill try the json of a normal user with the func u sent before and see if that does anything.

**Comment by 6uf** [comment]
![image](https://user-images.githubusercontent.com/86650306/170889667-e7d2564f-5641-4fd4-ad92-7462f16ae06a.png)
replacing your test with my own json string as shown above, it seems to be a issue with the emojis perhaps? idk what ur doing to make ur string work, im confused asf myself.

**Comment by 6uf** [comment]
```go
func ExampleMessage_ReadFrom() {
	var p = pk.Marshal(
		packetid.ClientboundChat,
		pk.String(`{"extra":[{"color":"white","text":"<"},{"color":"white","clickEvent":{"action":"open_url","value":"https://nmc.is/Leclu"},"hoverEvent":{"action":"show_text","value":[{"color":"white","text":"Normal"}]},"text":"§fLeclu§r"},{"color":"white","clickEvent":{"action":"open_url","value":"https://nmc.is/Leclu"},"hoverEvent":{"action":"show_text","value":[{"color":"white","text":"Normal"}]},"text":"> "},"",{"color":"white","text":"Dutch is a nice language ngl, its a hot soup of all the other european languages but its also one of"}],"text":""}`),
		pk.Byte(0),
		pk.UUID{},
	)

	var msg chat.Message
	if err := p.Scan(&msg); err != nil {
		panic(err)
	}
	fmt.Println(msg.ClearString())
}```

for debugging

**Comment by 6uf** [comment]
i was able to find the actual issue, after i removed the clickEvent and hoverEvent parts of the json it was able to parse properly, maybe theres a issue with a struct format?

**Comment by 6uf** [comment]
https://github.com/Tnze/go-mc/pull/202
