### ISSUE TITLE
minecraft update broke normal 0x03 packet for minecraft messages.

### ISSUE THREAD

**Issue by 6uf** [Tnze/go-mc#204]
**Describe the bug**

chat messages seem to have stopped working after a Minecraft update, no clue how to find the new packet id / formatting.

**To Reproduce**
1. Go Version: 1.18
2. GoMC Version: Latest release
3. Code:

```go
Conn.Conn.WritePacket(pk.Marshal(
	0x03,
	pk.String(e.Text()),
))
```

**Expected output**
Message to be sent in chat, doesn't work anymore.

**Comment by Tnze** [comment]
Minecraft version?

**Comment by 6uf** [comment]
it should be the default one within go-mc, idk how to change the mc version. 

my script worked previously with sending messages, i loaded up mc yesterday and noticed a update. then my script broke..

**Comment by Tnze** [comment]
So what's your server's version

**Comment by 6uf** [comment]
no im just a client joining a server. 

```go
Data.Conn = bot.NewClient()
basic.NewPlayer(Data.Conn, basic.DefaultSettings)
basic.EventListener{...}.Apply(Data.Conn)
```

etc.

my chat tui allows me to input text, which can then be used to send chat messages, its just a terminal chat system.. it worked fine and then yesterday it stopped working, logging in etc worked fine i could recv server messages and display them but after that it failed to actually send messages to the chat, maybe the protocol has changed?

**Comment by Tnze** [comment]
Yes, and the server should have a version number, what's it

**Comment by 6uf** [comment]
how would i get that information?

**Comment by 6uf** [comment]
![image](https://user-images.githubusercontent.com/86650306/171678536-0b9ac736-1f6f-4490-aaf4-717c4d2a30a8.png)

**Comment by 6uf** [comment]
yes no scripts, i can send messages.

i used packet 0x03 with pk.String() to send the packets, i find it weird because it was working fine then it doesnt anymore. perhaps they forced a update for the 1.19 protocol anyway?

**Comment by Tnze** [comment]
Even if they use 1.19, you should be fined when sending message which uses the serverbound packet.

**Comment by 6uf** [comment]
well idk what caused it then.. it was working fine.

**Comment by 6uf** [comment]
what does the 1.19 chat packet look like?

**Comment by Tnze** [comment]
https://wiki.vg/Pre-release_protocol

**Comment by 6uf** [comment]
![image](https://user-images.githubusercontent.com/86650306/171682558-2680f8cb-c8e7-4d5c-a227-0dbd35eace69.png)

shouldnt we use this?

**Comment by 6uf** [comment]
ive got it working

so yes, they defaulted the json formatting.. idk why they did this but

using this has worked
```go
if err := Data.Conn.Conn.WritePacket(pk.Marshal(
	0x03,
	pk.ByteArray([]byte(`{"text":"TEXT HERE"}`)),
)); err != nil {
	ui.Quit()
	panic(err)
}
```

**Comment by Tnze** [comment]
No! the protocol didn't change!

I don't know why your script is not working anymore. Are you handled every errors? Can it receive other's message now? Is `GameStart` event triggered?

**Comment by Tnze** [comment]
Okay

**Comment by Tnze** [comment]
What does "they defaulted the json formatting" means..?

**Comment by 6uf** [comment]
well the pk.String() returns no errors, but no messages appear in the chat box for me.. using the ByteArray with json works though

**Comment by Tnze** [comment]
And the server parse the json, you received a `TEXT HERE` message?

**Comment by 6uf** [comment]
well its weird because when i send `{"text":"TEXT HERE"}` this through, in the chat it only displays `{"text":""}`..

**Comment by 6uf** [comment]
wait i may be dumb.. i was getting a value from a input variable that isnt even a input variable, so its returning empty strings
lemme just check..

**Comment by Tnze** [comment]
I have no idea(
Can this behavior be reproduced by start a server.jar ourselves?

**Comment by 6uf** [comment]
atm im just logging into my acc and joining a server then attempting to send messages into the chat.

**Comment by 6uf** [comment]
do you have discord? i think itll be easier for communication.

**Comment by 6uf** [comment]
okay nvm, its a bug with the actual script sorry about this
