### ISSUE TITLE
Index out of bound when trying to unpack

### ISSUE THREAD

**Issue by eslym** [Tnze/go-mc#207]
**Describe the bug**
The index out of bound when trying to unpack a packet

**To Reproduce**
1. Go Version: go1.18.3 linux/amd64
2. GoMC Version: v1.18.2 h1:75dTJ0dJNI4V/7iG7Ze1pWkDmE9D02OQe6RfEZV0FBE=
3. Code:

https://github.com/eslym/anticopen/blob/36024f4b5783f25d286a2e28b545c50c6fd186e3/main.go#L76

**Expected output**
Not to have index out of bound

**Current output**

```
panic: runtime error: slice bounds out of range [:-1]

goroutine 6 [running]:
github.com/Tnze/go-mc/net/packet.(*Packet).unpackWithoutCompression(0xc00004bee0, {0x55d040, 0xc000010040})
   /home/xxx/go/pkg/mod/github.com/!tnze/go-mc@v1.18.2/net/packet/packet.go:176 +0x13f
github.com/Tnze/go-mc/net/packet.(*Packet).UnPack(0xc00005c180?, {0x55d040?, 0xc000010040?}, 0x0?)
   /home/xxx/go/pkg/mod/github.com/!tnze/go-mc@v1.18.2/net/packet/packet.go:154 +0x39
main.handleConnection({0x55dd70, 0xc000010040})
   /home/xxx/projects/go/anticopen/main.go:76 +0x105
created by main.main
   /home/xxx/projects/go/anticopen/main.go:67 +0x26a
```

**Context**
this was triggered by random port scanner, so i have totally no idea what's the actual data received

**Comment by Tnze** [comment]
I noticed you are using an old version of go-mc. The bug shouldn't exist in the latest version.

Our version management doesn't support fixing bugs in previous version. You could upgrade to the latest version or patch the package in this case.
