### ISSUE TITLE
RCON command tps to purpur mc server is empty

### ISSUE THREAD

**Issue by dirien** [Tnze/go-mc#208]
**Describe the bug**

When I use the RCON function of the library with a PurpurMC server the command `tps` returns an empty string.

I expect something like this:

```bash
[20:21:06 INFO]: [⚡] TPS from last 5s, 10s, 1m, 5m, 15m:
[20:21:06 INFO]: [⚡]  20.0, 20.0, 20.0, 20.0, 20.0
[20:21:06 INFO]: [⚡]
[20:21:06 INFO]: [⚡] Tick durations (min/med/95%ile/max ms) from last 10s, 1m:
[20:21:06 INFO]: [⚡]  7.3/55.7/122.6/122.6;  7.3/55.7/122.6/122.6
[20:21:06 INFO]: [⚡]
[20:21:06 INFO]: [⚡] CPU usage from last 10s, 1m, 15m:
[20:21:06 INFO]: [⚡]  0%, 0%, 0%  (system)
[20:21:06 INFO]: [⚡]  0%, 0%, 0%  (process)
```
**To Reproduce**
1. Go Version: 1.18.4
2. GoMC Version: main
3. Code:

```go


	conn, err := DialRCON("ip:25575", "test")
	if err != nil {
		panic(err)
	}
	defer conn.Close()

	err = conn.Cmd("tps")
	if err != nil {
		panic(err)
	}

	for {
		// Server may send the result in more(or less) than one packet.
		// See: https://wiki.vg/RCON#Fragmentation
		resp, err := conn.Resp()
		if err != nil {
			fmt.Print(err)
		}
		fmt.Printf("Server response: %q", resp)
		break
	}
```

**Expected output**
Output of the tps from the purpur server

**Current output**
Empty

**Additional context**
I use the purpurmc server version 1.19

**Comment by maxsupermanhd** [comment]
You tried with other rcon clients to do that?

**Comment by TMUniversal** [comment]
Output from [rcon-client](https://www.npmjs.com/package/rcon-client) (js):

```js
rcon.send("tps"):
```

```
§6TPS from last 5s, 1m, 5m, 15m: §a20.0, §a20.0, §a20.0, §a20.0
```


Snippet (as seen [here](https://www.npmjs.com/package/rcon-client#usage)):

```js
import { Rcon } from "rcon-client";

const rcon = await Rcon.connect({
  host: "localhost", port: 25575, password: "<password>"
})

console.log(await rcon.send("tps"));

rcon.end()
```

**Comment by maxsupermanhd** [comment]
Output seem to differ from what you would expect, perhaps that's some edge case...

**Comment by maxsupermanhd** [comment]
@dirien does the for loop hang? (it may hang and wait for replies or it may answer empty reply that would quit from the loop and not read any further)

**Comment by Tnze** [comment]
There is a for loop in your code. And a break at the last line which is weird.

**Comment by maxsupermanhd** [comment]
yeah, that's likely the reason, he might get an empty line or something

**Comment by Tnze** [comment]
You should move the `break` inside the `if err != nil` so that you could receive multiple response packet.

**Comment by Tnze** [comment]
> yeah, that's likely the reason, he might get an empty line or something

Our example in `rcon_test.go` is wrong.

**Comment by dirien** [comment]
Hi @Tnze,

I used the `rcon_test.go`, just for testing that it's not my code.

https://github.com/dirien/minecraft-prometheus-exporter/blob/e18886f20a4beb6e6145e87ca587369a1dc71ebc/pkg/exporter/exporter.go#L706

To verify, I tried https://github.com/Tiiffi/mcrcon also, and get an empty reponse back.

**Comment by Tnze** [comment]
> Hi @Tnze,
> 
> 
> 
> I used the `rcon_test.go`, just for testing that it's not my code.
> 
> 
> 
> https://github.com/dirien/minecraft-prometheus-exporter/blob/e18886f20a4beb6e6145e87ca587369a1dc71ebc/pkg/exporter/exporter.go#L706
> 
> 
> 
> To verify, I tried https://github.com/Tiiffi/mcrcon also, and get an empty reponse back.

I means you should repeatedly call `conn.Resp()` to receive the full response.

**Comment by dirien** [comment]
ahhh @Tnze, okay. But how do I know, on which command to loop through? And how long do i need to repeatedly call `conn.Resp()``

Sorry for the questions 😞

**Comment by Tnze** [comment]
> ahhh @Tnze, okay. But how do I know, on which command to loop through? And how long do i need to repeatedly call `conn.Resp()``


See: https://wiki.vg/RCON#Fragmentation
