### ISSUE TITLE
no licence?

### ISSUE THREAD

**Issue by fiws** [Tnze/go-mc#21]
would you consider licencing this project?

**Comment by Tnze** [comment]
I have no idea which one to choose.

**Comment by fiws** [comment]
maybe https://choosealicense.com/ can help. It would be awesome if you choose MIT or a similar permissive licence.

**Comment by fiws** [comment]
its nice that you licenced that project :+1: , but:

LGPL is very uncommon for a go library as it requires anything using your library to use the same licence. LGPL allows to circumvent this by using dynamic linking, but this is practically not possible with go libraries.

I accept if this is your final decision, but I just wanted to share that this is a showstopper for me.

**Comment by Tnze** [comment]
oh

**Comment by Tnze** [comment]
Is BSD a good choice?

**Comment by Tnze** [comment]
I will use MIT as you wishʕ •ᴥ•ʔ

**Comment by fiws** [comment]
awesome :tada:
