### ISSUE TITLE
Chat type is undefined

### ISSUE THREAD

**Issue by PekoNime** [Tnze/go-mc#213]
**Describe the bug**
First time clone from github and test running server example from repo https://github.com/go-mc/server

**To Reproduce**
1. Go Version: 1.19
2. GoMC Version: 1.18.3
3. Code:

```go
package main

import "github.com/Tnze/go-mc/chat"

func (c *Client) SendSystemChat(msg chat.Message, typeID chat.Type) {
	c.sendPacket(packetid.ClientboundSystemChat, msg, pk.VarInt(typeID))
}
```

**Expected output**
No errors and running server example https://github.com/go-mc/server

```
-
```

**Current output**
### github.com/go-mc/server/client
client\packets.go:221:63: undefined: chat.Type
client\packets.go:225:104: undefined: chat.Type

**Additional context**
The struct is missing?

**Comment by Tnze** [comment]
> go get github.com/Tnze/go-mc@master
