### ISSUE TITLE
How do I set a block to a specific x, y, z?

### ISSUE THREAD

**Issue by welcomehyunseo** [Tnze/go-mc#214]
Thank you for your project.
I am preparing to build a server with 1.14.4.
I need to send chunk data packets, but I know the player is moving. But it frequently fails to send chunk data packets.

How do I set a block to a specific x, y, z? And how to send the packet?

The reason I ask this question is because the setBlock function in level.chunk takes only index as a parameter.

```
func (s *Section) SetBlock(i int, v BlocksState) {
if block.IsAir(s.States.Get(i)) {
s.BlockCount--
}
if v != 0 {
s.BlockCount++
}
s.States.Set(i, v)
}
```

![image](https://user-images.githubusercontent.com/92869725/189517721-9e71d320-755d-448a-8db0-2fd3e4157266.png)

https://wiki.vg/index.php?title=Protocol&oldid=15346#Chunk_Data

I already understand block state id.

Please help me. I've been looking for it for several weeks, but it's a very difficult trip.

**Comment by Tnze** [comment]
Dup: #169

**Comment by Tnze** [comment]
Current implementation should be not to support 1.14 out of box. Best wishes for you.

**Comment by welcomehyunseo** [comment]
Thanks
