### ISSUE TITLE
server.PingInfo does not implement server.ListPingHandler

### ISSUE THREAD

**Issue by maxsupermanhd** [Tnze/go-mc#223]
(variable of type *server.PingInfo) as server.ListPingHandler value in struct literal: *server.PingInfo does not implement server.ListPingHandler (missing method MaxPlayer)compiler[InvalidIfaceAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#InvalidIfaceAssign)

**Comment by Tnze** [comment]
It's designed to be this. And to be used in this way:
https://github.com/go-mc/server/blob/af48477030d49d27c98aad22086eeb4dced8a3a6/main.go#L54-L57

**Comment by maxsupermanhd** [comment]
My bad I am stupid
