### ISSUE TITLE
Packet id is always 0

### ISSUE THREAD

**Issue by bblwbtd** [Tnze/go-mc#229]
**Describe the bug**

**To Reproduce**
1. Go Version: 1.19
2. GoMC Version:  latest
3. Code: 

```go
package main

import (
	"io"
	"log"
	"net"
)

type dummyWriter struct {

}

func (d dummyWriter) Write(p []byte) (n int, err error) {
	log.Println(p)
	return len(p), nil
}

func main() {
	addr, err := net.ResolveTCPAddr("tcp", ":25565")
	if err != nil {
		return
	}
	tcp, err := net.ListenTCP("tcp", addr)
	if err != nil {
		return
	}

	for {
		conn, err := tcp.AcceptTCP()
		if err != nil {
			return
		}

		go func() {
			rConn, err := net.Dial("tcp", "localhost:25566") //Change this to a real Minecraft server address
			if err != nil {
				log.Println(err)
				return
			}

			go func() {
				for {
					reader := io.TeeReader(conn, &dummyWriter{})
					_, err = io.Copy(rConn, reader)
					if err != nil {
						if err == io.EOF{
							break
						}
						log.Println(err)
					}
				}
			}()

			go func() {
				for {
					_, err = io.Copy(conn, rConn)
					if err != nil {
						log.Println(err)
						return
					}
				}
			}()

		}()
	}
}
```

I am trying to inspect the Minecraft packet with the library. I always receive the packet with id is 0 if the Minecraft version is 1.19.2. However, the packet id is correct if the Minecraft version is 1.17.1. I use the above code to output the packet of two different version. The server I used for Minecraft 1.19.2 is spigot. And I use the code in simpleServer1.17.1 in the example folder as the server for Minecraft 1.17.1.

This is the packets of Minecraft 1.17.1
<img width="794" alt="20221213 002327 (26 17 0 0 0 0 0 0 0 0 192 124 156 170 98 92 105 248 0 0 0 0 0 0" src="https://user-images.githubusercontent.com/39122737/207237099-faafc26f-6de6-4a9b-88b7-8bf7c674e681.png">

This is the packets of Minecraft 1.19.2
<img width="887" alt="Pasted Graphic 73" src="https://user-images.githubusercontent.com/39122737/207237113-97aff69a-e34b-486f-b078-322ed9b11c1b.png">

The first byte indicates how many bytes are in the packet. This is the same between the two versions. However, the second byte is different. In Minecraft 1.17.1, the second byte is the packet id. In Minecraft 1.19.2, the second byte is always 0. The go-mc library will consider the second byte as the packet id. As a result, the packet id is always 0 in Minecraft 1.19.2.

**Comment by Tnze** [comment]
Can you provide some code that import go-mc to explain your question?

Like how do you use go-mc and got a pk.Packet with ID == 0?

**Comment by bblwbtd** [comment]
I forget to handle the set compression packet so that the packet id is always 0. Everything works fine now.
