### ISSUE TITLE
Packet parsing layer

### ISSUE THREAD

**Issue by Lukasz825700516** [Tnze/go-mc#230]
Hi, so recently I wanted to write a small minecraft bot that would do some stuff, and I noticed that in `bot/basic/events.go` there is `EventsListener`, with a couple of boilerplate (packet deserialization) functions.

I suggest expanding this event listener, to accept more (all) types of packets, to reduce the burden on users for implementing deserialization.

The only issue I see would be requirement of providing separate Listener struct for each supported version of the protocol, so ideally it would need to be generated based on the game .jar, page of wiki.vg, or some up to date project providing in depth data about minecraft protocol.

I can volunteer in writing all these generators, so treat this issue as discussion about this feature, and how exactly it should be implemented.

**Comment by Tnze** [comment]
https://pkg.go.dev/github.com/Tnze/go-mc@v1.19.2/bot#Events.AddGeneric

**Comment by Lukasz825700516** [comment]
But from what I can tell this only registers packet handlers, and does not provide easy api for just setting func with parameters specific to given packet.

**Comment by Tnze** [comment]
Do you mean generating or hand-writing handler for all packets?

> to reduce the burden on users for implementing deserialization.

And that's the point?

**Comment by Lukasz825700516** [comment]
Yes

**Comment by Tnze** [comment]
So I separate the parsers into their own packages, like `bot/basic`, `bot/msg`, `bot/playerlist`. 
Then I can update them in batches and modules.

**Comment by Tnze** [comment]
Having a packet parsing layer is good. But you have to figure out how to generating them.

**Comment by Lukasz825700516** [comment]
I agree that some of the packets require some high level structures, but I think if there was some package providing structures like Slot from SetSlotContainer it should be doable. 
For generating, I already managed to "scrape" packages names from `net/minecraft/network/NetworkState.java` (using genSources from fabric example mod), with value types.

**Comment by Tnze** [comment]
> "scrape" packages names

https://github.com/Tnze/go-mc/blob/master/data/packetid/generator/Main.java

**Comment by Lukasz825700516** [comment]
haha, I guess its way better than grep and bunch of awk
