### ISSUE TITLE
How to get the type, state and content of a block/entity.

### ISSUE THREAD

**Issue by Paradist** [Tnze/go-mc#242]
**Say how this can be done or add functionality, please:**

I when updating a chunk get all the blocks, sift by type (for example pictures or frames) and get if a picture is an image(in `[]byte` or something else), if a frame and if a picture is in it - also in `[]byte` or something else.

So far my progress stopped at getting the number of blocks and their number in a chunk. From `stateId` I could not find how to get type and other information.

Please help!

**Comment by Tnze** [comment]
Didn't understand what do you want yet (picture is image etc.)

But if you got a state id now, probably you want to use it as an index of `block.StateList` then.

**Comment by Paradist** [comment]
I want to get an image in some format (like []bytes or something similar, which can then be saved as a .png/.jpg image) from a map and their coordinates in format (x y z).

**Comment by Tnze** [comment]
So can you access the full save files?

**Comment by maxsupermanhd** [comment]
> I want to get an image in some format from a map and their coordinates in format (x y z).


https://github.com/maxsupermanhd/WebChunk

**Comment by Paradist** [comment]
Hmm, I'll write more, I need to save "Frame Captcha" in .png/.jpg. For the normal(manual) is rarely used (And by the way, how do I get it out and save it too?).

I can't enter almost anywhere this way, because "Frame Captcha" is used almost everywhere.
