### ISSUE TITLE
How can I log in to the server

### ISSUE THREAD

**Issue by 223225zzzkkk** [Tnze/go-mc#244]
**Describe the bug**
使用examples/daze/daze.go实例文件时，chatHandler.SendMessage("/register lkjhgfdsa lkjhgfdsa"),无法注册，会直接发送到聊天栏
When using the examples/daze/daze. go instance file, chatHandler. SendMessage ("/register lkjhgfdsa lkjhgfdsa") cannot be registered and will be directly sent to the chat bar

**To Reproduce**
1. Go Version: 1.20
2. GoMC Version: 1.19.4-pre1
3. Code:
//其他代码没动过
//I haven't touched any other code before
func onGameStart() error {
	log.Println("Game start")
	if err := chatHandler.SendMessage("/register lkjhgfdsa lkjhgfdsa"); err != nil {
		return err
	}
	return nil // if err isn't nil, HandleGame() will return it.
}

func onSystemMsg(c chat.Message, overlay bool) error {
	log.Printf("System: %v, Overlay: %v", c, overlay)
	chatHandler.SendMessage("/register lkjhgfdsa lkjhgfdsa")
	return nil
}

**Expected output**

为什么会这样
```
THE OUTPUT OF PREVIOUS CODE
没成功过= =
<img width="164" alt="屏幕截图 2023-05-10 213321" src="https://github.com/Tnze/go-mc/assets/96153949/6f3173ce-f730-4e46-8141-ec6110324e3f">
<img width="692" alt="屏幕截图 2023-05-10 213336" src="https://github.com/Tnze/go-mc/assets/96153949/42d6b1a0-8db8-4846-b92c-2084393f4eb7">



**Current output**


**Additional context**
Add any other context about the problem here.

**Comment by Tnze** [comment]
发送命令现在是一个单独的包，跟聊天消息分开的

https://github.com/Tnze/go-mc/discussions/238

**Comment by 223225zzzkkk** [comment]
好

**Comment by 223225zzzkkk** [comment]
Chat Message是这个协议吗，如果是的话，该怎么编写其中的字段？我需要实例，抱歉，我是这方面的小白

**Comment by Tnze** [comment]
去看 #238
