### ISSUE TITLE
连接中断时怎么自动重新连接？

### ISSUE THREAD

**Issue by sikfeng** [Tnze/go-mc#25]
有时我想中断连接，然后让程序再连接。我式了在 `onDisconnect()` 里放 `c.JoinServer()`, 但程序还是终止了。因该怎么做呢？

`2019/09/13 02:19:51 Disconnect: Internal Exception: java.lang.ArrayIndexOutOfBoundsException: Index 17 out of bounds for length 7`
`2019/09/13 02:19:51 Login success`
(终止）

**Comment by Tnze** [comment]
可能你要自己写个支持取消的watchdog？

**Comment by sikfeng** [comment]
好吧，谢谢
