### ISSUE TITLE
Packet reading hangs and goes into infinite loop trying to read a packet

### ISSUE THREAD

**Issue by maxsupermanhd** [Tnze/go-mc#254]
**Describe the bug**
After updating to 1.19.4 (master) from 1.19.2 in certain condition bot hangs and infinitely reads same packet.

I have a discord bridge that has tab rendering:
https://github.com/maxsupermanhd/BlockBridge/tree/v762.0.0

Sometimes when I request a tab image from discord (/tab) it draws the tab perfectly fine but after that consumes 100% of one core and does not receive nor parse new packets and does not disconnect even if underlying connection is being killed by keepalive killer or closed by the server.

**Additional context**
It is not a race or threading issue, tested with -race and same result

**Comment by Tnze** [comment]
Do you know which loop is infinite?

**Comment by Tnze** [comment]
There are some guides using gdb to debug infinity loops:

```
gdb a.out
info threads
thread thread_id
info frame
```

**Comment by maxsupermanhd** [comment]
Yes, I know that HandleGame never exits, when adding debug logging it is being stuck at reading same packet again and again and again. It is trying to read chat.Message (the tab menu).

**Comment by maxsupermanhd** [comment]
I sent more debugging information in Discord. It seems like it actually reads from connection same packet and underlying conn and fd thinks it is connected (it is not)

**Comment by maxsupermanhd** [comment]
Ok, some very valuable information in my opinion:
![image](https://github.com/Tnze/go-mc/assets/20772987/cb35a7a7-e63e-4707-b102-bd7e25cdfb7f)
When connection pull fails it fails without setting an error and it causes it to reuse same packet over and over again because it is never updated in the first place
@Tnze Not funny!
