### ISSUE TITLE
Disconnected: receive queue is full

### ISSUE THREAD

**Issue by maxsupermanhd** [Tnze/go-mc#259]
**Describe the bug**
If server sends a LOT of packets bot drops connection due to queue being full

Related to how packet queue and reading is designed

**Comment by Tnze** [comment]
It's designed as is. But there is an important parameter that may be incorrectly estimated here.
https://github.com/Tnze/go-mc/blob/15478690a0faf85c1ee7e4d0046b71ccde02df21/bot/client.go#L55-L56

**Comment by Tnze** [comment]
The original design should have an API that allows you to configure the implementation scheme you want to use. But it's obvious that it hasn't been done yet.

**Comment by maxsupermanhd** [comment]
This is should not be enhancement but actual critical bug since it constantly disconnects.

**Comment by Tnze** [comment]
You didn't understand. Giving the ability of choosing the queues' implementation and capacity is an enhancement.

**Comment by maxsupermanhd** [comment]
How do I properly read packets Tnze? Reliably and with correct shutdown. One queue overflows, second breaks on socket closure, I can not reliably read packets.
