### ISSUE TITLE
Can I run any version of minecraft server with this project?

### ISSUE THREAD

**Issue by z0z0r4** [Tnze/go-mc#263]
Neither usage nor example could be found...Only client in example

I want to know the progress of the project

I noticed that the tag of v1.20 is preparing

找不到用法和示例，只找到客户端的操作...

我想了解下项目进展，它目前到哪个完整度了？

注意到 v1.20 正在准备中

**Comment by z0z0r4** [comment]
If not, what should I do to run it?

如果没法直接尝试启动一个完整的服务端，我应该怎么做？想贡献下

**Comment by Tnze** [comment]
这边目前能允许客户端登入、有登陆验证、KeepAlive、区块加载、方块实体（带数据的方块，如箱子）、聊天、显示附近其他玩家并实时同步位置

没做的功能有区块更新、实体系统、多世界切换等等

以上只是服务器方面的实现情况，服务端代码主要在/server目录，里面是个框架，要跑完整的代码在另一个repo，地址是github.com/go-mc/server

客户端主要是mc机器人，代码主要在/bot目录。为了降低工作量，设计上是只支持最新版本协议的。

其他目录主要是基础设施，如协议实现、静态和动态NBT库、方块表示、区块表示（调色板）、聊天消息格式等等感觉还算完善。

**Comment by z0z0r4** [comment]
也就是说对存档的操作以及实体相关操作都没有？

**Comment by z0z0r4** [comment]
~~初学 go…不觉得自己能做多少，在读仓库~~

**Comment by Tnze** [comment]
存档其实只差把玩家的放置和摧毁方块操作应用到区块上，只需要调用一下函数就可以了。
实体没有做，我不想像Java那样搞一堆类继承Entity父类什么的，但是Go里该怎么做还没想好。
储存实体数据的话可以直接用一个`nbt/dynbt.Value`值，dynbt是仿照fastjson的思路做的，性能很好。
比较难的是更新实体，写不好的话会变成屎山，当时是在考虑ECS之类的东西好不好用，搓了一个[基于原型的ECS实现](https://github.com/Tnze/go-ecs)，其实思路上还是不错的，但是API做出来用着不是很方便。
所以我在等Go什么时候支持写泛型方法，但是[那边](https://github.com/golang/go/issues/49085)讨论还根本没有结果，我看他们意思是讨论不出泛型方法怎么装箱进接口类型就不实现泛型方法。
最后就搁在这里了

**Comment by maxsupermanhd** [comment]
go-mc only "supports" version of minecraft that Tnze wants/needs. When there are critical bugs with infrastructure you are using with old versions those fixes will not be applied to them but directly onto new versions and only new versions.
I forked go-mc into go-vmc with aim to provide all major protocol versions like 1.20, 1.19.4, 1.18.2, 1.17.1 and so on.
However there is a project called ViaProxy that allows version translation on the fly so my approach is kinda questionable in regard to the protocol.
As Tnze already said there is no world generation, entity processing or anything like that and at the same time, considering how go-mc is advertised, I can understand how people are being mislead into believing that this is a complete replacement of the vanilla client/server.
What really blows my mind is how careless Tnze is, he rips stuff out from the codebase, he purposefully ignores serious architectural and technical mistakes and refuses to fix them. I myself submitted few pull requests before realizing that it is a pointless waste of time.
I don't think anything that Tnze makes can be reliable.

**Comment by Tnze** [comment]
谢谢你，打破语言障碍也要来黑我

**Comment by maxsupermanhd** [comment]
I think this piece of code answers all questions https://github.com/Tnze/go-mc/blob/master/bot/mcbot.go#L25

**Comment by z0z0r4** [comment]
虽然不知道这里双方有什么过节，我倒是不认为只支持某个特殊的版本会有什么问题

如你所见这是在重写 Minecraft，如果只支持某个版本毫无疑问能够在完成全部基础功能前更好的维护项目...

就算是 Java 的 bukkit 服务端分支也不乏只支持少数 Minecraft 版本的，这里似乎没有任何问题

> I think this piece of code answers all questions [`master`/bot/mcbot.go#L25](https://github.com/Tnze/go-mc/blob/master/bot/mcbot.go?rgh-link-date=2023-08-25T14%3A31%3A52Z#L25)我认为这段代码回答了所有问题 https://github.com/Tnze/go-mc/blob/master/bot/mcbot.go#L25

**Comment by z0z0r4** [comment]
> 存档其实只差把玩家的放置和摧毁方块操作应用到区块上，只需要调用一下函数就可以了。 实体没有做，我不想像Java那样搞一堆类继承Entity父类什么的，但是Go里该怎么做还没想好。 储存实体数据的话可以直接用一个`nbt/dynbt.Value`值，dynbt是仿照fastjson的思路做的，性能很好。 比较难的是更新实体，写不好的话会变成屎山，当时是在考虑ECS之类的东西好不好用，搓了一个[基于原型的ECS实现](https://github.com/Tnze/go-ecs)，其实思路上还是不错的，但是API做出来用着不是很方便。 所以我在等Go什么时候支持写泛型方法，但是[那边](https://github.com/golang/go/issues/49085)讨论还根本没有结果，我看他们意思是讨论不出泛型方法怎么装箱进接口类型就不实现泛型方法。 最后就搁在这里了

这个项目...目的是在 Go 上实现 Minecraft 吗？就服务端而言，看起来现在好散（

**Comment by z0z0r4** [comment]
值得考究（x

**Comment by Tnze** [comment]
原始目的是写一个Go程序，让它能加入官方的服务端

做完之后就在想，既然协议都实现了，为什么不做个服务端试试呢？所以就成了现在这样

觉得散的话，这是有意为之的，这不叫散，这叫低耦合🤔️

**Comment by z0z0r4** [comment]
🤔️ 未来可期，感觉很有希望弄出个服务端

我先把 Go 学熟练了再回来 ~~人高二，实在没时间 :(~~
