### ISSUE TITLE
Is there any way to send bundles of packets to the client in a thread safe way?

### ISSUE THREAD

**Issue by jobpaardekooper** [Tnze/go-mc#268]
**Is your feature request related to a problem? Please describe.**
The protocol includes a client bound [Bundle Delimiter](https://wiki.vg/Protocol#Bundle_Delimiter) to send packets to the client that should be processed in the same tick. The description from that wiki page discribes it as the following:

> The delimiter for a bundle of packets. When received, the client should store every subsequent packet it receives, and wait until another delimiter is received. Once that happens, the client is guaranteed to process every packet in the bundle on the same tick, and the client should stop storing packets. For example, this is used to ensure [Spawn Entity](https://wiki.vg/Protocol#Spawn_Entity) and [Set Entity Metadata](https://wiki.vg/Protocol#Set_Entity_Metadata) happen on the same tick.

Is there currently a way to use this feature in a thread safe way?

We can of course use this packet by just sending it using `conn.WritePacket` to indicate the start of the bundle. Then use `conn.WritePacket` to send some packets. Then we can indicate the end of the bundle with `conn.WritePacket`. But this is not thread safe. Of course nothing will break anything in a big way but if you have a multithreaded sever there is a chance these "Bundle Delimiters" get interleaved with ones from other threads. Which would basically defeat their purpose.

I was wondering if there is currently an API to write multiple packets at once?

**Comment by maxsupermanhd** [comment]
Unfortunately, as with everything in Tnze's go-mc library, if you want to deviate from original goals and vision of Tnze on how it should look+work you will have to essentially rewrite everything from scratch.

**Comment by jobpaardekooper** [comment]
I have also seen you arguing in some other issues? Whats the problem here?

**Comment by maxsupermanhd** [comment]
Problem is that go-mc is advertised as ultimate golang library for everything in minecraft but in reality it is just Tnze doing what he wants with 0 care about the others. Read issues themselves and discord conversations if you are interested.

**Comment by Tnze** [comment]
Such implement can be something better, but for the simplest way: Copy `net/queue.LinkedListQueue` and add methods like this:

```go
func (p *LinkedListQueue[T]) PushBundle(v ...T) bool {
	p.cond.L.Lock()
	if p.closed {
		panic("push on closed queue")
	}
	for _, vv := range v {
		p.queue.PushBack(vv)
	}
	p.cond.Signal()
	p.cond.L.Unlock()
	return true
}
```

The problem is hot to call this method when you have a `bot.Conn`. Feel free to clone and modify this library. If the solution works, you can create a PR to merge it to go-mc.

**Comment by Tnze** [comment]
Or maybe a better option is adding a `Mutex` for send queue in `bot.Conn`? And then extend the `WritePacket` method:
```go
func (c *Conn) WritePacket(packets ...pk.Packet) error {
	c.sendLock.Lock()
	defer c.sendLock.Unlock()
	for _, p := range packets {
		ok := c.send.Push(p)
		if !ok {
			return errors.New("queue is full")
		}
	}
	return nil
}
```

**Comment by jobpaardekooper** [comment]
Thanks for the example implementation. I was actually talking about `net.Conn` and the `WritePacket` on such a connection. Why is that not thread safe? It seems like it should be. In the end it just sends out things over the standard go `net.Conn` and that is thread safe.

**Comment by Tnze** [comment]
> Why is that not thread safe? It seems like it should be.

The thought is that a Mutex should protect process, rather than objects. So in the different logic layers we need different extent atomic operations promise, which means it may be required to add multiple Mutexs.

I want to let the user to choice write multiple threaded program or not. If your application is single threaded, the lock is not only useless but causing performance overhead, which is why `go-mc/net.Conn` doesn't have an internal lock -- You could add it yourself when needed.

> I don't think this would make much sense to support for the bot package because it is a client bound packet.

You are right. That's my mistake.
