### ISSUE TITLE
Can this library be used to create a server at this point?

### ISSUE THREAD

**Issue by StevenWilliams** [Tnze/go-mc#27]
Does this have chunk loader / map generation support? What else is missing to make a functional server?

**Comment by Tnze** [comment]
I'm thinking about how to represent a chunk. Then I can parse .mca file.

To make a server, we need update the chunks (tick), and Entity, and WorldGenerator, and everything else.

**Comment by Tnze** [comment]
Sure this lib can create a chat server now.
