### ISSUE TITLE
guys and girls, how do I update packet id to 1.20.4

### ISSUE THREAD

**Issue by qwqtoday** [Tnze/go-mc#276]
I am so close on updating go-mc to 1.20.4, I just need some help on the packet id thing, what is the correct way to update that?

**Comment by Tnze** [comment]
Do you see `data/packetid/generator/Main.java`?
It's a java program.

Basically, you should decompile the vanilla client or server (by use the MCP-Reborn project). Once you do so, you got a Gradle project opened in your IntelliJ IDEA IDE.

Now you copy the `Main.java` into the Maven project. The project view looks like this:
![image](https://github.com/Tnze/go-mc/assets/19628575/2de69bbc-4564-47dd-b305-915342315f9d)

Open the `Main.java` in your IDE. Click the green triangle on the left of the main function (or the Main class). Your IDEA will run the program. If there is any compile error, fix the error.

The program dumps the Packet names into stdout and you should copy them into `data/packetid/packetid.go`.

FInally, you should run `go generate` to generate `data/packetid/serverboundpacketid_string.go` and `data/packetid/clientboundpacketid_string.go`.
If you didn't install the `stringer` command, install it with `go install golang.org/x/tools/cmd/stringer`.

**Comment by qwqtoday** [comment]
Thanks, will try once I am back home

**Comment by qwqtoday** [comment]
Also another question, do you mind if I include a ping handler in bot/basic in that pr?

**Comment by Tnze** [comment]
I don't care as long as you do it right.

**Comment by qwqtoday** [comment]
I had done it. This is my pull request #277
Hopefully I did everything right.
