### ISSUE TITLE
how do I send a command to the server in 1.20.4

### ISSUE THREAD

**Issue by qwqtoday** [Tnze/go-mc#278]

**Comment by Tnze** [comment]
https://wiki.vg/Protocol#Chat_Command

**Comment by RepComm** [comment]
Using the wiki as well as this other issue as a guide:
https://github.com/Tnze/go-mc/issues/109

As well as the source of *msg.Manager.SendMessage

My code:

```go
line := "/say hi"
err := c.Conn.WritePacket(pk.Marshal(
	packetid.ServerboundChatCommand,
	pk.String(line),
))
```
Produces this error on the server, disconnecting the client:

```
[18:53:16 INFO]: Steve lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(9) + length(8) exceeds writerIndex(9): PooledUnsafeDirectByteBuf(ridx: 9, widx: 9, cap: 9)
[18:53:16 INFO]: Steve left the game

```

According the the wiki for the protocol 0x04 is the correct ID for this packet, which is the same value provided by the constant:
 
const packetid.ServerboundChatCommand packetid.ServerboundPacketID = 4

Just in case something weird was going on I also tried hard coding 0x04 in, with the same outcome.

What am I missing?

The Wiki for net protocol only suggests a single field in the packet for command string, yet the exception thrown suggests the server expects some other size of data given the packet id

FYI I'm running paper 1.20.2
[17:50:51 INFO]: Starting minecraft server version 1.20.2

And go-mc API version 1.20.2
github.com/Tnze/go-mc v1.20.2 // indirect

**Comment by RepComm** [comment]
I went digging using github repo search for ServerboundChatCommand const and found:

https://github.com/Tnze/go-mc/blob/300304eed30f1dce4420fd2e878ac65c3b697fa6/bot/msg/chat.go#L190

And decided to try and implement it the same way:

```go
stdchat.Start(func(line string) {
		if strings.HasPrefix(line, "/") {
			fmt.Println("sending command", line)
			
			var salt int64
			if err := binary.Read(rand.Reader, binary.BigEndian, &salt); err != nil {
				fmt.Println("couldn't gen salt for sending command to server", err)				
				return
			}

			line := strings.TrimPrefix(line, "/")

			err := c.Conn.WritePacket(pk.Marshal(
				packetid.ServerboundChatCommand,
				pk.String(line),
				pk.Long(time.Now().UnixMilli()),
				pk.Long(salt),
				pk.Ary[pk.VarInt]{Ary: []pk.Tuple{}},
				sign.HistoryUpdate{
					Acknowledged: pk.NewFixedBitSet(20),
				},
			))

			if err != nil {
				fmt.Println("failed to send command", err)
			}
			
		} else {
			fmt.Println("sending chat", line)
			chatm.SendMessage(line)
		}
	})
```
And that seemed to work just fine.. The wiki does not mention needing the fields after the String, so I have no idea why it works unless the wiki is out dated for 1.20.2

**Comment by RepComm** [comment]
I went ahead and simplified this into it's own function:

```go
func SendChatCommand(cmd string, conn *bot.Conn) error {
	var salt int64
	if err := binary.Read(rand.Reader, binary.BigEndian, &salt); err != nil {
		return errors.Join(
			errors.New("couldn't gen salt for sending command to server"),
			err,
		)
	}

	cmd = strings.TrimPrefix(cmd, "/")

	return conn.WritePacket(pk.Marshal(
		packetid.ServerboundChatCommand,
		pk.String(cmd),
		pk.Long(time.Now().UnixMilli()),
		pk.Long(salt),
		pk.Ary[pk.VarInt]{Ary: []pk.Tuple{}},
		sign.HistoryUpdate{
			Acknowledged: pk.NewFixedBitSet(20),
		},
	))
}

```

Example usage:
```go
line := "/say hi"
if strings.HasPrefix(line, "/") {
	fmt.Println("sending command", line)
	
	err := SendChatCommand(line, c.Conn)
	if err != nil {
		fmt.Println("failed to send command", err)
	}
	
} else {
	fmt.Println("sending chat", line)
	chatm.SendMessage(line)
}

```

**Comment by Tnze** [comment]
> The wiki does not mention needing the fields after the String.

Wiki for 1.20.2: https://wiki.vg/index.php?title=Protocol&oldid=18641#Chat_Command
