### ISSUE TITLE
1.21 Support?

### ISSUE THREAD

**Issue by OfflinePing** [Tnze/go-mc#282]
**Is your feature request related to a problem? Please describe.**
It seems like it can't connect to 1.21. Servers. I would love to see that

**Describe the solution you'd like**
I want it to be able to connect to 1.21 Servers and maybe select the Protocol Version Programmatically

**Comment by Tnze** [comment]
See readme.md

**Comment by Tnze** [comment]
See #58

**Comment by OfflinePing** [comment]
> See readme.md
> See #58

So I understood the Multiple Protocol part that it's just too much work to implement. But 1.21 Support, I don't see anything in the README except the Downloading 1 Version below the current one. For 1.21 that would be 1.20.6 wich is not a branch here. Means not planned as of right now?

**Comment by OfflinePing** [comment]
go get github.com/Tnze/go-mc@master works with latest Minecraft Version.
