### ISSUE TITLE
Any sort of documentation?

### ISSUE THREAD

**Issue by miam-miam100** [Tnze/go-mc#3]
I love your tool but is there a place where I can see all the functions you implemented (not only the examples you have supplied)

**Comment by Tnze** [comment]
The [godoc](https://godoc.org/github.com/Tnze/go-mc) is what you need.

**Comment by Tnze** [comment]
At present, there is mainly including `UseItem()`, `Chat()` and `SwingArm()` functions. For events, they are
```go
GameStart    func() error
ChatMsg      func(msg chat.Message, pos byte) error
Disconnect   func(reason chat.Message) error
HealthChange func() error
Die          func() error
SoundPlay    func(name string, category int, x, y, z float64, volume, pitch float32) error
```
These are enough for creating a chat or fishing bot. But no more complex bot like auto-mine which need chunk data parsing, moving animation generate and NBT parsing for item manage.

I'm interested in implementing them but there are too much work to do. I will try my best.

**Comment by miam-miam100** [comment]
Thanks so much!!!
Hopefully you'll be able to add those features as that would be amazing !
