### ISSUE TITLE
有考虑加使用代理功能的计划吗

### ISSUE THREAD

**Issue by Sunbread** [Tnze/go-mc#31]
这样机器人就可以更简单地使用代理服务器，而不需要第三方软件。

**Comment by Tnze** [comment]
如果你是想通过代理连接mc服务器的话，很简单。
用到`golang.org/x/net/proxy`包，
```go
dialer, err := proxy.SOCKS5("tcp", "127.0.0.1:9742", nil, proxy.Direct)
if err != nil {
	 log.Fatalf("can't connect to the proxy:", err)
}
```

对于go-mc/net来说，它只需要一个conn。
```go
// func DialMC(addr string) (*Conn, error) {
	conn, err := dialer.Dial("tcp", addr)
	return &Conn{
		Socket:     conn,
		ByteReader: bufio.NewReader(conn),
		Writer:     conn,
	}, err
// }
```

**Comment by Sunbread** [comment]
> 如果你是想通过代理连接mc服务器的话，很简单。
> 用到`golang.org/x/net/proxy`包，
> 
> ```go
> dialer, err := proxy.SOCKS5("tcp", "127.0.0.1:9742", nil, proxy.Direct)
> if err != nil {
> 	 log.Fatalf("can't connect to the proxy:", err)
> }
> ```
> 
> 对于go-mc/net来说，它只需要一个conn。
> 
> ```go
> // func DialMC(addr string) (*Conn, error) {
> 	conn, err := dialer.Dial("tcp", addr)
> 	return &Conn{
> 		Socket:     conn,
> 		ByteReader: bufio.NewReader(conn),
> 		Writer:     conn,
> 	}, err
> // }
> ```

你的方法必须修改go-mc/net.DialMC的代码吗？

**Comment by Tnze** [comment]
不用，你自己Dial然后套一个Conn出来就行了
```go
conn, _ := dialer.Dial(.......)
mcConn := &net.Conn{conn, bufio.NewReader(conn), conn}
```

**Comment by Sunbread** [comment]
> 不用，你自己Dial然后套一个Conn出来就行了
> 
> ```go
> conn, _ := dialer.Dial(.......)
> mcConn := &net.Conn{conn, bufio.NewReader(conn), conn}
> ```

https://github.com/Tnze/go-mc/blob/05b7a48f870e2bc011cc63773ed5c8212e28adaf/bot/mcbot.go#L19
我希望bot.JoinServer也能使用代理，但是你这一行会覆盖Client.conn……

**Comment by Tnze** [comment]
这么说来`bot`包当前确实设计得不太好。  
不过写它的时候也只是想做个例子……

**Comment by Sunbread** [comment]
另外yggdrasil有什么无需修改库源代码的办法使用代理吗？

**Comment by Tnze** [comment]
很明显没有……

**Comment by Sunbread** [comment]
> 很明显没有……

yggdrasil.client可以考虑改成yggdrasil.Client，或者加一个获取yggdrasil.client的函数，这样就能上代理了。

**Comment by Sunbread** [comment]
已于#32实现

**Comment by Tnze** [comment]
yggdrasil.Client让我再想想。如果用SetClient方法的话yggdrasil包就会变成一个状态机，不太好。
