### ISSUE TITLE
handle packet 0x14 error: inventory len not match

### ISSUE THREAD

**Issue by Stefatorus** [Tnze/go-mc#4]
Getting the error when joining a server

https://sfy.cx/ss/u/bc97.txt

**Comment by Tnze** [comment]
I'm sorry I've been busy lately.I'll see it in two weeks.
Try to remove line 104 in file ingame.go .

**Comment by Tnze** [comment]
![QQ20190720-104827@2x.png](https://i.loli.net/2019/07/20/5d32814b94bd055270.png)
No problem with me. Can you take a screenshot of what's in the player's backpack?

**Comment by ramdan1523** [comment]
Well it work with me

**Comment by unlimitedcoder2** [comment]
I am also having this issue [img](https://gamergirlp.ee/i/5ccb.png)
```go
err = c.HandleGame()
if err != nil {
	fmt.Printf("Error handling game logic, %s", err.Error());
}
```

**Comment by Tnze** [comment]
So please take a screenshot for the player's inventory😥

**Comment by unlimitedcoder2** [comment]
https://gamergirlp.ee/i/zk6w.png

**Comment by ramdan1523** [comment]
Idk will it work for you because i fix it in 1.14.1. Ask tnze he is the one help me

**Comment by Tnze** [comment]
Well I commendably fix this at [fed2cf2](https://github.com/Tnze/go-mc/commit/fed2cf25ce5b91c3221f36a547a9c4917dad108f)  (laugh）

**Comment by ramdan1523** [comment]
I don't understand why u laugh

**Comment by Tnze** [comment]
Because I just ban that function.
![NTOE46YPH2K9BS)VDKQWNBQ](https://user-images.githubusercontent.com/19628575/62375434-e08fdd00-b570-11e9-9ec9-d4d182843bee.jpg)

**Comment by ramdan1523** [comment]
U know what i don't care anymore because i don't even understand

**Comment by Tnze** [comment]
Windows and Slots... 
Now we leave it to the person who responds to the event. This problem won't bother us any more.

**Comment by unlimitedcoder2** [comment]
I am still having this issue on v1.14.3 [Image](https://discock.gg/eda29a195fc344b9.png)
```
Received BungeeCord from minecraft:register
Logged in
Received BungeeCord (Hypixel) from minecraft:brand
Received HYP|McVersion  from minecraft:register
Received vanilla from minecraft:brand
MSG:
MSG:
Error: handle packet 0x14 error: inventory len not match
```
MSG: is chat message
Recieved is plugin message
Inventory looks like https://discock.gg/CCa9D5bda00b90B0.png
and hotbar is https://discock.gg/bb7Cd2d6fbC6eFe4.png

**Comment by Tnze** [comment]
That's known problem and fixed at https://github.com/Tnze/go-mc/commit/c667d86153c63248a5a0a689221fecd9c7759a99

May be you wanna fork v1.14.3 and replay this commit.

**Comment by unlimitedcoder2** [comment]
If this is fixed in the latest version why does this error still occur? I'm new to go but when I did `go get github.com/Tnze/go-mc` or something like that doesn't it gets the most recent version from git?

**Comment by Tnze** [comment]
try `go get github.com/Tnze/go-mc@master`?
I am not sure.

**Comment by Tnze** [comment]
To update an package you should use `go get -u github.com/Tnze/go-mc` maybe.
