### ISSUE TITLE
How to view player inventory and surrounding terrain

### ISSUE THREAD

**Issue by yassinrais** [Tnze/go-mc#40]
hey ! 
i just want to know how to get Inventory player items

like list of items 

also how to get the blocks arround the player 

thanks ^_^

**Comment by Tnze** [comment]
Thank you for your compliment.

To get inventory player items, handle `c.Events.WindowsItem` event. When window ID equals 0, the received window is player's inventory.

You can see [wiki.vg](https://wiki.vg/Protocol#Window_Items) about `WindowItems` packet for more details. Especially if you found my handler is broken, you can use `c.Events.ReceivePacket`.

**Comment by Tnze** [comment]
Surrounding terrain......  
Lookup `c.Wd.Chunks`？ It should still work normally.

**Comment by yassinrais** [comment]
Thanks you for answer

i have tried with chunks but it really hard to know the coordinates of blocks (x,y,z) if it possible


Thanks

**Comment by Tnze** [comment]
Take a look at this?
https://github.com/Tnze/go-mc/blob/5740edd409224f528d91ad80ca6546cf49004714/bot/world/world.go#L51

**Comment by yassinrais** [comment]
Nice .. i understand now good .. 
Thanks you bro !

**Comment by yassinrais** [comment]
When i use 	
`c.Events.WindowsItem = onWindowItem`
it not work for me 
`Time Interval Update :
2020/02/25 21:34:09 Error Fatal : HandleGame
 <nil>
exit status 1`


Code : 
`func onWindowItem(id byte, slots []entity.Slot ) error{
	
	log.Println("Count : ",slots)

	return nil	
}`

Thanks.

**Comment by Tnze** [comment]
Please send the complete code.😬

**Comment by yassinrais** [comment]
Take :) 

https://pastebin.com/yNkbDfsS

my idea it was to check the bot items to search food 

and eat it

**Comment by Tnze** [comment]
I have tested the WindowItem event. Looks like the NBT parse logic was broken. When player pick up an Item without NBT, it return a TagEnd error.

> ```
> Time Interval Update :
> 2020/02/25 21:34:09 Error Fatal : HandleGame
>       <nil>
> exit status 1
> ```
But I didn't see any one like that

**Comment by Tnze** [comment]
I'll keep watching tomorrow

**Comment by yassinrais** [comment]
Okey ! thanks you ^^

**Comment by yassinrais** [comment]
yo ! 💯 

so is the are any news ?

thanks.

**Comment by Tnze** [comment]
Looks like wiki.vg is crashed?

**Comment by Tnze** [comment]
Yes, there is a bug which fixed there just right now: https://github.com/Tnze/go-mc/compare/5740edd409224f528d91ad80ca6546cf49004714...7defd6062c6a7214e3abea841bb60a91d688ad0f

**Comment by Tnze** [comment]
Wait, it's like the problem hasn't been solved

**Comment by Tnze** [comment]
OK, it works.

**Comment by yassinrais** [comment]
Ok , thank you for this update :)
