### ISSUE TITLE
Panic at c.Chat()

### ISSUE THREAD

**Issue by Genanik** [Tnze/go-mc#41]
This is the error which ide tell me:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12a0c6e]
goroutine 42 [running]:
github.com/Tnze/go-mc/bot.(*Client).Chat(0x0, 0x134bd32, 0x4, 0x1, 0x1)
        ~/Desktop/go-mc/bot/motion.go:81 +0xce
main.watchDog()
        ~/Desktop/go-mc/cmd/Chat/Chat.go:94 +0x15e
```

I try to change autofish.go to make it can show me chat msg on server

This is code I changed:
```go
func onGameStart() error {
	log.Println("Game start")
	watch = make(chan time.Time)
	go watchDog()
	return nil
}
func watchDog() {
	to := time.NewTimer(time.Second * timeout)
	for {
		select {
		case <-watch:
		case <-to.C:
			log.Println("raply")
			if err := c.Chat("test"); err != nil {
				panic(err)
			}
		}
		to.Reset(time.Second * timeout)
	}
}
```
Thanks!

**Comment by Tnze** [comment]
You should not call `c.Chat()` at there. Start a goroutine at `onGameStart`.
```go
func onGameStart() error {
	log.Println("Game start")

	watch = make(chan time.Time)
	go watchDog()

	go func() {
		for {
			c.Chat("hello")
			time.Sleep(time.Second)
		}
	}

	return c.UseItem(0)
}
```

**Comment by Genanik** [comment]
> You should not call `c.Chat()` at there. Start a goroutine at `onGameStart`.
> 
> ```go
> func onGameStart() error {
> 	log.Println("Game start")
> 
> 	watch = make(chan time.Time)
> 	go watchDog()
> 
> 	go func() {
> 		for {
> 			c.Chat("hello")
> 			time.Sleep(time.Second)
> 		}
> 	}
> 
> 	return c.UseItem(0)
> }
> ```

ok, I will try

**Comment by Tnze** [comment]
Make sure if `c` is not `nil` when you call `c.Chat()`.

**Comment by Tnze** [comment]
Very sorry about that `bot` package is not improve and perfect. There is a plan about rebuild it at `github.com/go-mc`, but I haven't started yet.😥

**Comment by Genanik** [comment]
Never mind, this is complex😉

**Comment by Genanik** [comment]
thx, I use `c := bot.NewClient()`before. I replaced it to `c = bot.NewClient()` this, and it work!!!!!
