### ISSUE TITLE
Can't use v1.15 tag

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [Tnze/go-mc#42]
I am trying to get the v1.15 version of the bot, but go will immediately change it to v1.15.1 in the go.mod file. Changing the version to v1.15.0 does not work either.

A solution would be to add a v1.15.0 tag for minecraft v1.15.

**Comment by Tnze** [comment]
Okay

**Comment by HoLLy-HaCKeR** [comment]
It seems to work now, thank you very much :)
