### ISSUE TITLE
Movement

### ISSUE THREAD

**Issue by yyewolf** [Tnze/go-mc#43]
```
func (g *Client) SetPosition(x, y, z float64, onGround bool) error {
 	g.Player.X, g.Player.Y, g.Player.Z = x, y, z
 	g.Player.OnGround = onGround
	g.conn.WritePacket(pk.Marshal(
		0x12,
		pk.Double(x),
		pk.Double(y),
		pk.Double(z),
		pk.Boolean(true),
	))
	
	recv, err := g.conn.ReadPacket()
	if err != nil {
		fmt.Errorf("bot: recv list packect fail: %v", err)
		return nil
	}
	var t pk.VarInt
	err = recv.Scan(&t)
	if err != nil {
		return nil
	}
	
	g.conn.WritePacket(pk.Marshal(
		0x00,
		t,
	))
	
	return nil
}

```
I cannot get this code to work, I'm not really used to Minecraft Protocol so I'm not sure of how to do this

**Comment by Tnze** [comment]
Which minecraft version are you using?

**Comment by yyewolf** [comment]
I adapted the bot to 20w09a which uses the same protocol as the latest supported version.
By the way I updated my function to : 
```
func (g *Client) SetPosition(x, y, z float64, onGround bool) error {
 	g.X, g.Y, g.Z = x, y, z
	g.OnGround = onGround
 	sendPlayerPositionAndLookPacket(g)
	return nil
}
```

2020/02/29 11:02:02 Disconnect: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/17 (a) was larger than I expected, found 8 bytes extra whilst reading packet 17

This is the error I get

**Comment by Tnze** [comment]
Maybe mojang change something which is not documented?

**Comment by yyewolf** [comment]
I don't think so, changes have been documented already :/

**Comment by Tnze** [comment]
I remember that server doesn't response a `Player Position And Rotation` packet, except client wants to move a wrong position.

And, does wiki.vg show that PlayerPosition ID is `0x11` ?

**Comment by yyewolf** [comment]
Yes it does

**Comment by Tnze** [comment]
But you wrote `0x12`.

**Comment by yyewolf** [comment]
Oh well, I did change the code to :

`func (g *Client) SetPosition(x, y, z float64, onGround bool) error {
 	g.X, g.Y, g.Z = x, y, z
	g.OnGround = onGround
 	sendPlayerPositionAndLookPacket(g)
	return nil
}`

And : 
```
func sendPlayerPositionAndLookPacket(c *Client) {
	c.conn.WritePacket(pk.Marshal(
		0x11,
		pk.Double(c.X),
		pk.Double(c.Y),
		pk.Double(c.Z),
		pk.Float(c.Yaw),
		pk.Float(c.Pitch),
		pk.Boolean(c.OnGround),
	))
}

```
 
The error is still the same

**Comment by Tnze** [comment]
Seems not right, you should send `0x11` without Yaw and Pitch, or `0x12` with Yaw and Pitch. That's what "Rotation" means.

**Comment by yyewolf** [comment]
Okay, I changed that, there's no error but no movement either

**Comment by Tnze** [comment]
If your movement is not rational, server may reject your move. In this case, server send a `Player Position And Look (clientbound)` packet to correct client location. Client then send same position packet back as a confirmation.

**Comment by yyewolf** [comment]
I'll try to move one block

**Comment by yyewolf** [comment]
After a quick check, it indeed correct the position, how could I fix that ?

**Comment by Tnze** [comment]
Try to interpolate in one block. Maybe 0.1 block per packet?

**Comment by yyewolf** [comment]
Doesn't work either, also it doesn't save the X position in c.X for some reasons

**Comment by Tnze** [comment]
> Oh well, I did change the code to :
> 
> ```
> func (g *Client) SetPosition(x, y, z float64, onGround bool) error {
>  	g.X, g.Y, g.Z = x, y, z
> 	g.OnGround = onGround
>  	sendPlayerPositionAndLookPacket(g)
> 	return nil
> }
> ```
> 
> And :
> 
> ```
> func sendPlayerPositionAndLookPacket(c *Client) {
> 	c.conn.WritePacket(pk.Marshal(
> 		0x11,
> 		pk.Double(c.X),
> 		pk.Double(c.Y),
> 		pk.Double(c.Z),
> 		pk.Float(c.Yaw),
> 		pk.Float(c.Pitch),
> 		pk.Boolean(c.OnGround),
> 	))
> }
> ```
> 
> The error is still the same

Seems like you didn't handle the error from `conn.WritePacket`?

Would you check if server send `Player Position And Look (clientbound)`?

**Comment by yyewolf** [comment]
It does send it and there's no error returned

**Comment by Tnze** [comment]
Then I have no idea for the time being.

**Comment by yyewolf** [comment]
Okay, thank you, I'll try to find a solution !

**Comment by AmIJesse** [comment]
I was running into a similar issue today, whenever I would send a player movement packet I would just teleport back to my original position. After a ton of testing/messing around I found out that if you modify your c.Physics.X,Y,Z coordinates before sending the packet it works properly.

```
c.Physics.Pos.X = x
c.Physics.Pos.Y = y
c.Physics.Pos.Z = z

c.Conn().WritePacket(packet.Marshal(
	data.PositionServerbound,
	packet.Double(x),
	packet.Double(y),
	packet.Double(z),
	packet.Boolean(true),
))
```

**Comment by Tnze** [comment]
I think this is not a mistake in the implementation of the network protocol, but a problem about how the client generates the location information recognized by the server. To completely solve this problem may need the participation of physical engine.

The issue will now be closed.
