### ISSUE TITLE
Suggestion: Implement the context and Finite State Machine

### ISSUE THREAD

**Issue by hcrgm** [Tnze/go-mc#45]
I'm writing a virtual Minecraft server based on this package. Since there is no any information about connection state (i.e. FSM), I have to wrap the provided net.Conn to implement connection state.  

What's more, sharing data between different connection states and goroutines seems difficult as no context has provided. For example, I want to share the protocol version, keepalive id data and so on between Play connection state and goroutine that is used to send keepalive packet repeatly so that I can measure the latency between server and client.  

Implement a context may be a good choice, it could solve problems mentioned above. How about your idea?

**Comment by Tnze** [comment]
设计是这样的，net包的Conn只是单纯的连接，它只包含是否启用了压缩之类的简单状态。Conn基本上是全版本通用的。

你提到的协议版本、KeepAlive等等，或许应该自己实现一个Client来实现？

**Comment by hcrgm** [comment]
> 设计是这样的，net包的Conn只是单纯的连接，它只包含是否启用了压缩之类的简单状态。Conn基本上是全版本通用的。
> 
> 你提到的协议版本、KeepAlive等等，或许应该自己实现一个Client来实现？

emm...我在写服务端，不是客户端。不过net/http包下的Request和Server不是都有Context嘛，我觉得这么设计理论上是可以的，但我不太清楚在这个场合套用http的理论合不合理

**Comment by Tnze** [comment]
额，你说你在写一个Status Ping Server，这个到底是你的服务器给MC服务器发请求呢，还是你的服务器就是MC服务器，要接受游戏客户端的连接？

**Comment by hcrgm** [comment]
> 额，你说你在写一个Status Ping Server，这个到底是你的服务器给MC服务器发请求呢，还是你的服务器就是MC服务器，要接受游戏客户端的连接？

模拟一个mc服务器接受连接。可是其实status也要state的呀

**Comment by Tnze** [comment]
```
type Player struct {
        X, Y, Z float64
        // .....
        Client struct {
                keepAlive ......
                net.Conn
        }
}
```

在Conn里面包装关于KeepAlive之类的功能是没有必要的，因为在一些简单的场景中不需要这些功能。只有当连接进入了Play状态之后这些才有意义。

在这种情况下再给net.Conn包一层Client结构用来表示连接进来的一个客户端，如果只是Ping的话直接拿着Conn处理就好了。

我觉得不是应该把玩家信息保存在Conn里面，然后服务器里拿着Conn到处用，而是把Conn储存在玩家对象里面，处理玩家的时候再作为底层调用它。

**Comment by hcrgm** [comment]
> ```
> type Player struct {
>         X, Y, Z float64
>         // .....
>         Client struct {
>                 keepAlive ......
>                 net.Conn
>         }
> }
> ```
> 
> 在Conn里面包装关于KeepAlive之类的功能是没有必要的，因为在一些简单的场景中不需要这些功能。只有当连接进入了Play状态之后这些才有意义。
> 
> 在这种情况下再给net.Conn包一层Client结构用来表示连接进来的一个客户端，如果只是Ping的话直接拿着Conn处理就好了。
> 
> 我觉得不是应该把玩家信息保存在Conn里面，然后服务器里拿着Conn到处用，而是把Conn储存在玩家对象里面，处理玩家的时候再作为底层调用它。

嗯, 说的确实如此, 我调整为遍历玩家发keepalive了. 我重新思考了一下, 我wrap的Conn其实可以调整为名为Server的struct, 在 Server 里实现 Context, 一些数据往 Player 塞.
然后我就想不通 Player 到底放哪里呢, 处理各种包的逻辑我不可能只写在一个 func里面, 我还是要包装一下Conn才行...然后把 Player 放到自己包装的 Conn
我的理解是 go-mc/net.Conn 是底层的连接, 专注于收发包而不管别的, 包装后的 Conn 用来执行各种逻辑, 有点像官方服务器中 PlayerConnection 类和 NetworkManager 类的关系, 不知道有没有理解对...
可是在 go-mc/net.Conn 实现连接状态还是必要的吧, 因为在 Login 状态之前是不知道玩家名的, 不可能在这状态之前就创建个 Player 对象吧...

**Comment by Tnze** [comment]
或许可以把连接的状态隐藏在程序处理流程里。

比如在登入的时候直接拿着Conn处理login，等进入play状态之后再把Conn包装成Player传递给程序后面的部分来处理。

**Comment by hcrgm** [comment]
> 或许可以把连接的状态隐藏在程序处理流程里。
> 
> 比如在登入的时候直接拿着Conn处理login，等进入play状态之后再把Conn包装成Player传递给程序后面的部分来处理。

这样状态不就变成了只有两种了吗, 这样Status就变得不好处理了

**Comment by Tnze** [comment]
Status不好处理是指？Ping返回的列表？

维护个在线玩家列表呗

**Comment by hcrgm** [comment]
> Status不好处理是指？Ping返回的列表？
> 
> 维护个在线玩家列表呗

对, 是Ping返回的列表.
我确有一个在线玩家列表.
客户端可以很容易地切换状态, 客户端要么走Handshake->Status流程, 要么走Handshake->Login->Play流程, 但服务端要按Handshake包的nextstate分情况处理, 必须界定好状态. 如果不显示表达连接状态, 就不好判断了, 判断Player是否nil?

**Comment by Tnze** [comment]
很简单，玩家列表是[]Player，不是[]Conn。

用if判断nextstate，如果是要list，就调用处理list的函数，读取全局的玩家列表并返回服务器状态；如果是play，就调用处理login的函数，然后将玩家添加入玩家列表，并且构造Player继续处理，这时候才添加到全局的玩家列表中，

**Comment by hcrgm** [comment]
emm...好吧, 我大概弄明白你的意思了, 状态维护的事可能是像我这样的使用者应该干的事
我还想讨论下哪种设计会好点
```go
type Server struct {
	playerList......
}
type PlayerConn struct {
	mcnet.Conn
	player *Player
	State
}
func (s *Server) Start() error {
	// 监听
	for {
		// 接受连接
		go s.handleConnection(mcnet.Conn)
		// 等待下一个连接
	}
}

func (s *Server) handleConnection(conn mcnet.Conn) {
	defer conn.Close()
	for {
		// 持续读包
		pk, err := conn.ReadPacket()
		// 错误处理
		// 然后这里怎么判断状态, 所有的包都会传入这个方法
		// 肯定不能只判断包 ID 吧, 不同状态下 ID 对应的包是不同的
		// 也不能break, 这样连接就断了
		pc := &PlayerConn{conn,nil}
		// 如果Handshake->Status和Handshake->Login->Play的中间过程不是阻塞的
		// (显示表示状态)
		switch pc.State {
		case HANSHAKE:
			pc.handleXXX(ok)
		case STATUS:
			pc.handleXXX(pk)
		case LOGIN:
			pc.handleXXX(pk)
		case PLAY:
			pc.handleXXX(pk)
		}
		// 如果切换状态的中间过程是阻塞的(隐式表达状态)
		// 方法阻塞, 直到读包出错/处理包出错
		if pk.ID == 0x00 {
			if nextstate == 1 {
				c.handleStatus()
			} else {
				c.handleLogin()
			}
		}
	}
}
func (c *PlayerConn) handleXXX() error {
	// 假设这是处理list的函数, 那这个函数状态切换过程应该是阻塞的
	// 我觉得阻塞不太好
	pk, err := c.ReadPacket()
	......
}
func (c *PlayerConn) handleXXX(pk packet.Packet) error {
	// 如果是状态切换过程是非阻塞的
	pk, err := c.ReadPacket()
	......
	c.State = Login
	// 切换Login状态, 然后handleConnection执行下一个读包的循环
	return nil
}
```
阻塞处理隐含状态 vs 非阻塞处理显示表达状态?

**Comment by Tnze** [comment]
阻塞goroutine开销不大，Go就是这么设计的。

按照逻辑顺序写吧。

**Comment by hcrgm** [comment]
感谢指导😄
另外我开了一个新的issue, 用英语交流吧, 这样有相同问题的外国朋友能很快找到
