### ISSUE TITLE
Add WriteFields func to Packet, to make packet construction more flexible

### ISSUE THREAD

**Issue by hcrgm** [Tnze/go-mc#46]
I generally use `packet.Marshal()` to create a packet.
But recently I encountered a issue: The packet's fields and their order may be different in different protocol version.
For example, Packet `Join Game`:
Structure in 1.15.2:

Packet ID | State | Bound To
-- | -- | --
0x26 | Play | Client

Field Name | Field Type | Notes
-- | -- | --
Entity ID | Int | The player's Entity ID (EID)
Gamemode | Unsigned Byte | 0: Survival, 1: Creative, 2: Adventure, 3: Spectator. Bit 3 (0x8) is the hardcore flag.
Dimension | Int Enum | -1: Nether, 0: Overworld, 1: End; also, note that this is not a VarInt but instead a regular int.
Hashed seed | Long | First 8 bytes of the SHA-256 hash of the world's seed.
Max Players | Unsigned Byte | Was once used by the client to draw the player list, but now is ignored
Level Type | String Enum (16) | default, flat, largeBiomes, amplified, customized, buffet, default_1_1
View Distance | VarInt | Render distance (2-32)
Reduced Debug Info | Boolean | If true, a Notchian client shows reduced information on the debug screen. For servers in development, this should almost always be false.
Enable respawn screen | Boolean | Set to false when the doImmediateRespawn gamerule is true

Structure in 1.12.2:

Packet ID | State | Bound To
-- | -- | --
0x23 | Play | Client

Field Name | Field Type | Notes
-- | -- | --
Entity ID | Int | The player's Entity ID (EID)
Gamemode | Unsigned Byte | 0: Survival, 1: Creative, 2: Adventure, 3: Spectator. Bit 3 (0x8) is the hardcore flag.
Dimension | Int Enum | -1: Nether, 0: Overworld, 1: End; also, note that this is not a VarInt but instead a regular int.
Difficulty | Unsigned Byte | 0: peaceful, 1: easy, 2: normal, 3: hard
Max Players | Unsigned Byte | Was once used by the client to draw the player list, but now is ignored
Level Type | String Enum (16) | default, flat, largeBiomes, amplified, default_1_1
Reduced Debug Info | Boolean | If true, a Notchian client shows reduced information on the debug screen. For servers in development, this should almost always be false.

There are some obvious diffreences between them.
If I accept multi protocol versions, I may code like this:
```go
var pk packet.Packet
// protocover 578 represents mc 1.15.2, 340 represents mc 1.12.2
if protover == 578 {
	pk = packet.Marshal(0x26, field1, field2...)
} else if protover == 340 {
	pk = packet.Marshal(0x23, field1, field2...)
}
// sendPacket...
```
But I want to make it more flexible:
```go
pk := packet.Marshal(getPacketIdByProtocol(protover))
pk.WriteFields(entityId, gameMode, dimension)
if protover == 578 {
	// Write the field that belongs to packet Join Game in protocol version 578
	pk.WriteFields(hashedSeed)
}
pk.WriteFields(maxPlayers, levelType)
......
// sendPacket......
```
If there is no function used to add fields to the packet, We may code like this:
```go
pk.Data = append(pk.Data, fields...)
if protover == 578 {
	// Write the field that belongs to packet Join Game in protocol version 578
	pk.Data = append(pk.Data, hashedSeed)
}
pk.Data = append(pk.Data, fields...)
// sendPacket...
```
So might we add some func to make it simpler?

**Comment by Tnze** [comment]
What about

```go
func writeFields(p *pk.Packte, fields ...FieldEncoder) {
	for _, v := range fields {
		pk.Data = append(pk.Data, v.Encode()...)
	}
}
```

**Comment by hcrgm** [comment]
> What about
> 
> ```go
> func writeFields(p *pk.Packte, fields ...FieldEncoder) {
> 	for _, v := range fields {
> 		pk.Data = append(pk.Data, v.Encode()...)
> 	}
> }
> ```

It's okay. How about make it public?
```go
func WriteFields(p *pk.Packet, fields ...FieldEncoder) {
	for _, v := range fields {
		pk.Data = append(pk.Data, v.Encode()...)
	}
}
```
Allow others to use it

**Comment by Tnze** [comment]
Think about it, it might not be a good way to support multi-version.
Instead, definition a interface named `PacketGenerator`, then implement it for each version.

But it is still necessary to make the way of constructing packet more flexible. For those packet contain "Optional Field", which need known of context.

**Comment by hcrgm** [comment]
Yeah I got it. It's just a simple example and I shall implement a complex packet handling system based on `packet` package (not yet, my time is limited). Looking forward to your new idea about the better design to make packet construction more flexible

**Comment by theoo3** [comment]
How far back will these implemented versions go?
