### ISSUE TITLE
WindowItem : Add Items like food , etc ... 

### ISSUE THREAD

**Issue by yassinrais** [Tnze/go-mc#47]
WindowItem : some block info missed (empty item in array)

**Comment by Tnze** [comment]
My suggestion is that dump the data by yourself. Follow the steps in `data/items.go`, you can generate data from the latest server.jar directly from minecraft.

**Comment by yassinrais** [comment]
yes, I'm still learning golang ,  learn more and more
because after working with a lot of language 
this one is complicated 

because of the memory save tips , unused value,...... 
It's hard , but i will do my best :D

thanks for answering

**Comment by Tnze** [comment]
Well, in my opinion, golang is a simple language. It's easy to learn, but might be different with other language on the logical module. So when you learn a concept, learn it as a new one. 

Relax, it's easy~
