### ISSUE TITLE
about AttackEntity

### ISSUE THREAD

**Issue by x1aole1** [Tnze/go-mc#48]
AttackEntity(entityID int32, hand int)，这里需要一个整数型的id，但是现在的实体id都是类似iron_golem 之类的，1.14之后不能用数字id了，这里应该写什么？

**Comment by x1aole1** [comment]
如果能回答万分感激

**Comment by Tnze** [comment]
这个实体ID是当你接收一个Spawn Entity包的时候服务端会给你发的一个ID，不是用来指定实体类型的ID。
