### ISSUE TITLE
Install command?

### ISSUE THREAD

**Issue by ramdan1523** [Tnze/go-mc#5]
I tried:
go get github.com/Tnze/go-mc

It didn't work, what should in do?

**Comment by Tnze** [comment]
Because there are no go files in the project root directory, you should try `go get github.com/Tnze/go-mc/net` or other sub package. The whole project will be pulled down.

**Comment by ramdan1523** [comment]
U answer this in the other issue

**Comment by ramdan1523** [comment]
It didn't work

**Comment by ramdan1523** [comment]
Well good think im smart i already found a way to download using wget

**Comment by ramdan1523** [comment]
But other may need ur help

**Comment by Tnze** [comment]
any output？

**Comment by ramdan1523** [comment]
Path output

**Comment by ramdan1523** [comment]
I test it again it say nothing

**Comment by Tnze** [comment]
That does mean you have successfully get the package.Try `go get -v github.com/Tnze/go-mc`.

**Comment by ramdan1523** [comment]
Yes because i use wget maybe it will say something if i delete it

**Comment by Tnze** [comment]
Why are you using wget. Nobody downloads packages by wget. Use go get or git clone.

在 2019年7月26日，上午11:55，ramdan1523 <notifications@github.com<mailto:notifications@github.com>> 写道：


Yes because i use wget maybe it will say something if i delete it

**Comment by ramdan1523** [comment]
IDK

**Comment by ramdan1523** [comment]
Wget can download everything
