### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by seupedro** [Tnze/go-mc#51]
Hi! First of all, congrats for your excelent work.

I would like to somehow donate to this project keep going. Can you create a patreon or something like that?

I haven't even test this lib in my server. But I'm guessing this is exactly what i was looking for.

**Comment by Tnze** [comment]
Thank you so much for your this kind offer.

In my country, pateon or PayPal is not very convenient. I can provide a WeChat Reward Code, which can scan by [WeChat](https://www.wechat.com/). What I need more than donations is to feedback and good ideas. Feel free to submit issue or pull request~

I would be happy if this lib could help you.
![3DF98723-E3ED-4082-858C-AACD4C2A2807](https://user-images.githubusercontent.com/19628575/79094925-93187080-7d8b-11ea-8dc4-52da6ac77f83.jpeg)
