### ISSUE TITLE
Invalid block id's in c.Wd.Chunk

### ISSUE THREAD

**Issue by Joeri-G** [Tnze/go-mc#56]
I am using this library to write a farm bot and I noticed that the block ID's I was getting were wrong. At first I thought that it was an issue with my own code but when I dumped `c.Wd.Chunks` I noticed impossible id's like 6190 and 3999 in places where they should've been 152 and 89.

I dumped the chunk as follows.
```
var chunk = c.Wd.Chunks[world.ChunkLoc{X:chunkX, Z:chunkZ}]
var cString = fmt.Sprintf("%+v\n", chunk)
log.Println(cString)
```

Another thing that I noticed is that in order to get specific blocks out of the Chunk, attributes that are not exported (like `Chunk.sections`) need to be accessed. In the file `world.go` a function called `getBlock` exists that can do this, but in the current version it is commented out.

**Comment by Tnze** [comment]
That's not an error, because the returned value is not a `block id` but a `status id`. Represent all the status of a block but not only the block type.

You could use `github.com/Tnze/go-mc/data/`.  Then `data.BlockNameByID[6190] == "minecraft:redstone_block"` is what you want

**Comment by Tnze** [comment]
Could you pease help me test #57 ? thanks!

**Comment by Tnze** [comment]
Sorry for the delay, the new API is available on https://github.com/Tnze/go-mc/commit/cfd8d6b870bbf2d561a7552045788e2cfec3b489 now.
