### ISSUE TITLE
multiple protocol versions

### ISSUE THREAD

**Issue by rur0** [Tnze/go-mc#58]
Hi, thanks for creating and posting this library :)

This is more of a question not an issue, but are there plans for adding multiple protocol support? 
Since for example many servers still use <1.11

**Comment by Tnze** [comment]
No, adding multiple protocol support needs a lots of work and make it difficult to maintain.
But on the other hand, only the `go-mc/bot` and `go-mc/data` package is not crossing versions. What you should do is using `go-mc/net` package and send/receive packets by your self, just like what `go-mc/bot` does.
