### ISSUE TITLE
shouldn't the packet implementation use VarInt for the packet id?

### ISSUE THREAD

**Issue by fiws** [Tnze/go-mc#59]
I'm just wondering if the [packet ID](https://github.com/Tnze/go-mc/blob/master/net/packet/packet.go#L12) which currently is a `byte` should be a `VarInt` instead.

wiki.vg defines the Packet id as VarInt: https://wiki.vg/Protocol#Packet_format

Not sure if I'm interpreting something wrong here.

**Comment by Tnze** [comment]
It's.....look like you are right! It should be defined as `int32` because Java's `Int` means 32-bit.

Maybe I should fix it in next version?
Between 0 and 127, both Byte and VarInt are the same. It shouldn't be a big problem for now.

**Comment by fiws** [comment]
yes, i don't think it's a big deal. 

i wanted to use a custom packet id in a project, but it's pretty complicated (on the minecraft side). No luck so far.

nice that you are addressing it though! :+1:

**Comment by Tnze** [comment]
Fixed in #63 .
