### ISSUE TITLE
How to play older 1.14 version?

### ISSUE THREAD

**Issue by ramdan1523** [Tnze/go-mc#6]
The client only allow 1.14.4 but my server not yet updated (still 1.14.1)
Anyone know how to change version?

**Comment by Tnze** [comment]
There are tags for every version of this repository. You can `go get github.com/Tnze/go-mc@1.14.1` to use the 1.14.1 version. Anyway, the old version may have some bugs.

**Comment by ramdan1523** [comment]
TY

**Comment by ramdan1523** [comment]
Also ty for telling me the download command

**Comment by ramdan1523** [comment]
TY
