### ISSUE TITLE
RCONClientConn should have a Close function

### ISSUE THREAD

**Issue by DeadlySurgeon** [Tnze/go-mc#64]
`RCONClientConn` in `./net` should have `Close() error` to match with `io.Closer` since it holds onto a TCP connection.

**Comment by Tnze** [comment]
Good idea. But this function definition is not necessary.
```go
func (r *RCONConn) Close() error {
	return r.Conn.Close()
}
```
The compiler will automatically` conn.Conn.Close ()` expanded into `conn.Close ()`

**Comment by DeadlySurgeon** [comment]
@Tnze Should be good.
