### ISSUE TITLE
How to login with using compass?

### ISSUE THREAD

**Issue by ramdan1523** [Tnze/go-mc#7]
Every time someone chat my command deleted and after i write something it didn't get sended (im using 1.14.1 maybe that's the problem, if it is the problem plss update the old client).

**Comment by Tnze** [comment]
Show me your code.

**Comment by ramdan1523** [comment]
I change the daze proxy to the server then it connected but i can't chat

**Comment by ramdan1523** [comment]
Do i need command for chat

**Comment by ramdan1523** [comment]
Im using ubuntu 19.04

**Comment by Tnze** [comment]
emmmm.
The daze example can’t send msg yet. It only receives and print chat.

**Comment by Tnze** [comment]
```
func sendChat(g *bot.Client) {
	console := bufio.NewScanner(os.Stdin)
	for console.Scan() {
		err := g.Chat(console.Text())
		if err != nil {
			log.Println(err)
		}
	}
	if err := console.Err(); err != nil {
		log.Println(err)
	}
}
```
Then `go sendChat(c)` at main func

**Comment by ramdan1523** [comment]
What should i use

**Comment by Tnze** [comment]
Write your code.

**Comment by ramdan1523** [comment]
Go send chat code?

**Comment by Tnze** [comment]
Read messages from console and do c.Chat(msg) by programming.

**Comment by ramdan1523** [comment]
Do i need to write the go sendchat function in the daze.go

**Comment by ramdan1523** [comment]
Or just write the command in console

**Comment by Tnze** [comment]
The “go” is one of statement of Golang.

**Comment by Tnze** [comment]
> ```
> func sendChat(g *bot.Client) {
> 	console := bufio.NewScanner(os.Stdin)
> 	for console.Scan() {
> 		err := g.Chat(console.Text())
> 		if err != nil {
> 			log.Println(err)
> 		}
> 	}
> 	if err := console.Err(); err != nil {
> 		log.Println(err)
> 	}
> }
> ```
> 
> 
> Then `go sendChat(c)` at main func

Copy my code.

**Comment by ramdan1523** [comment]
Yes?

**Comment by ramdan1523** [comment]
What did u mean go sendchat at main function

**Comment by Tnze** [comment]
```go
func main() {
          ........
          go sendChat()

          err := c.HandleGame()
          if err ....
          ......
}
```

**Comment by ramdan1523** [comment]
TY

**Comment by ramdan1523** [comment]
Then how to send msg

**Comment by Tnze** [comment]
Write in the console and press Enter

**Comment by ramdan1523** [comment]
Thats it?

**Comment by Tnze** [comment]
Sure

**Comment by ramdan1523** [comment]
Do i also need to write err or only the go senchat

**Comment by ramdan1523** [comment]
Ummmmm
It broke the the client

**Comment by ramdan1523** [comment]
# command-line-arguments
./daze.go:34:10: c.Events.PluginMessagae undefined (type bot.eventBroker has no field or method PluginMessagae)
./daze.go:44:13: undefined: bufio
./daze.go:44:30: undefined: os

**Comment by Tnze** [comment]
Basic Golang language question.
```go
import (
      "os"    //  <- add this
      "bufio" //  <- and this
)
```

**Comment by ramdan1523** [comment]
A new one
# command-line-arguments
./daze.go:36:10: c.Events.PluginMessagae undefined (type bot.eventBroker has no field or method PluginMessagae)
./daze.go:39:13: not enough arguments in call to sendChat
        have ()
        want (*bot.Client)

**Comment by ramdan1523** [comment]
Pressed 

A new one
# command-line-arguments
./daze.go:36:10: c.Events.PluginMessagae undefined (type bot.eventBroker has no field or method PluginMessagae)
./daze.go:39:13: not enough arguments in call to sendChat
        have ()
        want (*bot.Client)

**Comment by ramdan1523** [comment]
Is there no easier way then changing script

**Comment by ramdan1523** [comment]
I can give u ssh access

**Comment by MscBaiMeow** [comment]
Can you show me all your code？I‘ll correct it and send it back to you.

**Comment by ramdan1523** [comment]
The Script?

**Comment by MscBaiMeow** [comment]
yes

**Comment by MscBaiMeow** [comment]
and golang isn't a kind of script.
https://en.wikipedia.org/wiki/Go_(programming_language)

**Comment by ramdan1523** [comment]
package main

import (
        "log"

        "os"
        "bufio"
        "github.com/Tnze/go-mc/bot"
        "github.com/Tnze/go-mc/chat"
        // "github.com/Tnze/go-mc/authenticate"
)

func main() {
        c := bot.NewClient()
        // For online-mode, you need login your Mojang account
        // and load your Name and UUID to client:
        //
        //      auth, err := authenticate.Authenticate("Your E-mail", "Your Password")
        //      if err != nil {
        //              panic(err)
        //      }
        //      c.Name, c.Auth.UUID, c.AsTk =  auth.SelectedProfile.Name, auth.SelectedProfile.ID, auth.AccessToken

        //Login
        err := c.JoinServer("www.ironcreeper.com", 25565)
if err != nil {
                log.Fatal(err)
        }
        log.Println("Login success")

        //Regist event handlers
        c.Events.GameStart = onGameStart
        c.Events.ChatMsg = onChatMsg
        c.Events.Disconnect = onDisconnect
        c.Events.PluginMessagae = onPluginMessage

        //JoinGame
        go sendChat()

        err = c.HandleGame()
        if err != nil {
                log.Fatal(err)
        }
}

func sendChat(g *bot.Client) {
        console := bufio.NewScanner(os.Stdin)
        for console.Scan() {
                err := g.Chat(console.Text())
                if err != nil {
log.Println(err)
        }
}

func onGameStart() error {
        log.Println("Game start")
        return nil //if err isn't nil, HandleGame() will return it.
}

func onChatMsg(c chat.Message, pos byte) error {
        log.Println("Chat:", c)
        return nil
}

func onDisconnect(c chat.Message) error {
        log.Println("Disconnect:", c)
        return nil
}

func onPluginMessage(channel string, data []byte) error {
        log.Println("PluginMessage", channel, data)
        return nil
}

**Comment by MscBaiMeow** [comment]
go ```
package main

import (
        "log"

        "os"
        "bufio"
        "github.com/Tnze/go-mc/bot"
        "github.com/Tnze/go-mc/chat"
        // "github.com/Tnze/go-mc/authenticate"
)

func main() {
        c := bot.NewClient()
        // For online-mode, you need login your Mojang account
        // and load your Name and UUID to client:
        //
        //      auth, err := authenticate.Authenticate("Your E-mail", "Your Password")
        //      if err != nil {
        //              panic(err)
        //      }
        //      c.Name, c.Auth.UUID, c.AsTk =  auth.SelectedProfile.Name, auth.SelectedProfile.ID, auth.AccessToken

        //Login
        err := c.JoinServer("www.ironcreeper.com", 25565)
if err != nil {
                log.Fatal(err)
        }
        log.Println("Login success")

        //Regist event handlers
        c.Events.GameStart = onGameStart
        c.Events.ChatMsg = onChatMsg
        c.Events.Disconnect = onDisconnect
        c.Events.PluginMessage = onPluginMessage

        //JoinGame
        go sendChat(c)

        err = c.HandleGame()
        if err != nil {
                log.Fatal(err)
        }
}

func sendChat(g *bot.Client) {
        console := bufio.NewScanner(os.Stdin)
        for console.Scan() {
                err := g.Chat(console.Text())
                if err != nil {
log.Println(err)
        }
}
}

func onGameStart() error {
        log.Println("Game start")
        return nil //if err isn't nil, HandleGame() will return it.
}

func onChatMsg(c chat.Message, pos byte) error {
        log.Println("Chat:", c)
        return nil
}

func onDisconnect(c chat.Message) error {
        log.Println("Disconnect:", c)
        return nil
}

func onPluginMessage(channel string, data []byte) error {
        log.Println("PluginMessage", channel, data)
        return nil
}
```

**Comment by MscBaiMeow** [comment]
``` go
package main

import (
        "log"

        "os"
        "bufio"
        "github.com/Tnze/go-mc/bot"
        "github.com/Tnze/go-mc/chat"
        // "github.com/Tnze/go-mc/authenticate"
)

func main() {
        c := bot.NewClient()
        // For online-mode, you need login your Mojang account
        // and load your Name and UUID to client:
        //
        //      auth, err := authenticate.Authenticate("Your E-mail", "Your Password")
        //      if err != nil {
        //              panic(err)
        //      }
        //      c.Name, c.Auth.UUID, c.AsTk =  auth.SelectedProfile.Name, auth.SelectedProfile.ID, auth.AccessToken

        //Login
        err := c.JoinServer("www.ironcreeper.com", 25565)
if err != nil {
                log.Fatal(err)
        }
        log.Println("Login success")

        //Regist event handlers
        c.Events.GameStart = onGameStart
        c.Events.ChatMsg = onChatMsg
        c.Events.Disconnect = onDisconnect
        c.Events.PluginMessage = onPluginMessage

        //JoinGame
        go sendChat(c)

        err = c.HandleGame()
        if err != nil {
                log.Fatal(err)
        }
}

func sendChat(g *bot.Client) {
        console := bufio.NewScanner(os.Stdin)
        for console.Scan() {
                err := g.Chat(console.Text())
                if err != nil {
log.Println(err)
        }
}
}

func onGameStart() error {
        log.Println("Game start")
        return nil //if err isn't nil, HandleGame() will return it.
}

func onChatMsg(c chat.Message, pos byte) error {
        log.Println("Chat:", c)
        return nil
}

func onDisconnect(c chat.Message) error {
        log.Println("Disconnect:", c)
        return nil
}

func onPluginMessage(channel string, data []byte) error {
        log.Println("PluginMessage", channel, data)
        return nil
}
```

**Comment by ramdan1523** [comment]
TY
I hope it work

**Comment by Tnze** [comment]
Basic golang teaching time😏

**Comment by MscBaiMeow** [comment]
![](https://i.loli.net/2019/07/26/5d3afc71c67c124717.jpg)

**Comment by ramdan1523** [comment]
Is this meme time

**Comment by ramdan1523** [comment]
The msg still getting deleted when other chat

**Comment by ramdan1523** [comment]
I get disconnected after using command 

2019/07/26 13:43:35 handle packet 0x16 error: server set slot error
exit status 1

**Comment by Tnze** [comment]
How can other delete your message? Your msg is there or it didn't ever get sent.

**Comment by ramdan1523** [comment]
Are u guys Chinese

**Comment by ramdan1523** [comment]
My msg is there but i can't see it. It get sended if i press enter

**Comment by Tnze** [comment]
> I get disconnected after using command
> 
> 2019/07/26 13:43:35 handle packet 0x16 error: server set slot error
> exit status 1

That might be a bug which fix at the later version.

**Comment by ramdan1523** [comment]
:(

**Comment by ramdan1523** [comment]
The readme txt say there are move and swing

**Comment by Tnze** [comment]
Clean your 背包 can avoid that : )

**Comment by ramdan1523** [comment]
I don't understand Chinese

**Comment by ramdan1523** [comment]
What is the command

**Comment by ramdan1523** [comment]
2019/07/26 13:52:11 bot: read packet fail: read len of packet fail: EOF
exit status 1

**Comment by MscBaiMeow** [comment]
背包 means inventory

**Comment by ramdan1523** [comment]
To join server we use compass

**Comment by ramdan1523** [comment]
Also the server use login command which give the compass

**Comment by ramdan1523** [comment]
:(

**Comment by MscBaiMeow** [comment]
```  go
package main

import (
	"log"

	"bufio"
	"github.com/Tnze/go-mc/bot"
	"github.com/Tnze/go-mc/chat"
	"os"
	// "github.com/Tnze/go-mc/authenticate"
)

func main() {
	c := bot.NewClient()
	// For online-mode, you need login your Mojang account
	// and load your Name and UUID to client:
	//
	//      auth, err := authenticate.Authenticate("Your E-mail", "Your Password")
	//      if err != nil {
	//              panic(err)
	//      }
	//      c.Name, c.Auth.UUID, c.AsTk =  auth.SelectedProfile.Name, auth.SelectedProfile.ID, auth.AccessToken

	//Login
	err := c.JoinServer("www.ironcreeper.com", 25565)
	if err != nil {
		log.Fatal(err)
	}
	log.Println("Login success")
	if err := c.Chat("/login xxxxxx"); err != nil {
		log.Println(err)
	}
	if err := c.UseItem(0); err != nil {
		log.Println(err)
	}
	//Regist event handlers
	c.Events.GameStart = onGameStart
	c.Events.ChatMsg = onChatMsg
	c.Events.Disconnect = onDisconnect
	c.Events.PluginMessage = onPluginMessage

	//JoinGame
	go sendChat(c)

	err = c.HandleGame()
	if err != nil {
		log.Fatal(err)
	}
}

func sendChat(g *bot.Client) {
	console := bufio.NewScanner(os.Stdin)
	for console.Scan() {
		err := g.Chat(console.Text())
		if err != nil {
			log.Println(err)
		}
	}
}

func onGameStart() error {
	log.Println("Game start")
	return nil //if err isn't nil, HandleGame() will return it.
}

func onChatMsg(c chat.Message, pos byte) error {
	log.Println("Chat:", c)
	return nil
}

func onDisconnect(c chat.Message) error {
	log.Println("Disconnect:", c)
	return nil
}

func onPluginMessage(channel string, data []byte) error {
	log.Println("PluginMessage", channel, data)
	return nil
}

```
change "/login xxxxxx" to your login command

**Comment by Tnze** [comment]
Not right

**Comment by ramdan1523** [comment]
?

**Comment by ramdan1523** [comment]
Still error 
2019/07/26 14:28:11 bot: read packet fail: read len of packet fail: EOF
exit status 1

**Comment by ramdan1523** [comment]
I need to sleep
I will continue tomorrow

**Comment by ramdan1523** [comment]
I can give ssh access if needed

**Comment by ramdan1523** [comment]
Still crash

**Comment by ramdan1523** [comment]
2019/07/26 23:41:53 handle packet 0x16 error: server set slot error                                                   exit status 1

**Comment by Tnze** [comment]
See issue #4.

**Comment by ramdan1523** [comment]
What

**Comment by MscBaiMeow** [comment]
I visited your server just now.I found that player should click an item after use the compass.However the bot is not able to do it.I have corrected the code that you can enter the server,but I'm sorry that I couldn't help continuely.You should look up https://wiki.vg/Protocol#Click_Window to know how to send a packets that tell the server your clicked something.

**Comment by ramdan1523** [comment]
:(

**Comment by MscBaiMeow** [comment]
"handle packet 0x16 error: server set slot error" maybe a bug which will be fixed next version
I have no way know

**Comment by MscBaiMeow** [comment]
``` go
package main

import (
	"time"
	"log"
	"bufio"
	"github.com/Tnze/go-mc/bot"
	"github.com/Tnze/go-mc/chat"
	"os"
	// "github.com/Tnze/go-mc/authenticate"
)

var c *bot.Client

func main() {
	c = bot.NewClient()
	c.Auth = bot.Auth{
		Name: "Msc_BaiMeow",
	}
	// For online-mode, you need login your Mojang account
	// and load your Name and UUID to client:
	//
	//      auth, err := authenticate.Authenticate("Your E-mail", "Your Password")
	//      if err != nil {
	//              panic(err)
	//      }
	//      c.Name, c.Auth.UUID, c.AsTk =  auth.SelectedProfile.Name, auth.SelectedProfile.ID, auth.AccessToken

	//Login
	err := c.JoinServer("www.ironcreeper.com", 25565)
	if err != nil {
		log.Fatal(err)
	}
	log.Println("Login success")
	//Regist event handlers
	c.Events.GameStart = onGameStart
	c.Events.ChatMsg = onChatMsg
	c.Events.Disconnect = onDisconnect
	c.Events.PluginMessage = onPluginMessage

	//JoinGame
	go sendChat()

	err = c.HandleGame()
	if err != nil {
		log.Fatal(err)
	}
}

func sendChat() {
	console := bufio.NewScanner(os.Stdin)
	for console.Scan() {
		err := c.Chat(console.Text())
		if err != nil {
			log.Println(err)
		}
	}
}

func onGameStart() error {
	time.Sleep(time.Second*1)
	if err := c.Chat("/login 123654"); err != nil {
		return err
	}
	if err := c.UseItem(0); err != nil {
		return err
	}
	log.Println("Game start")
	return nil //if err isn't nil, HandleGame() will return it.
}

func onChatMsg(c chat.Message, pos byte) error {
	log.Println("Chat:", c)
	return nil
}

func onDisconnect(c chat.Message) error {
	log.Println("Disconnect:", c)
	return nil
}

func onPluginMessage(channel string, data []byte) error {
	log.Println("PluginMessage", channel, data)
	return nil
}
```
with the code you can login in the server but the bug hasn't been fixed.

**Comment by ramdan1523** [comment]
K

**Comment by ramdan1523** [comment]
I will wait until this server updated

**Comment by ramdan1523** [comment]
Wtf

**Comment by ramdan1523** [comment]
It say you have 4 account one of them is not my its ur

**Comment by ramdan1523** [comment]
Lol

**Comment by Tnze** [comment]
To fix this bug, simply remove this line :) https://github.com/Tnze/go-mc/blob/bfb5e51f243fa6db1e598c61788e7f437c283caf/bot/ingame.go#L120

**Comment by Tnze** [comment]
> It say you have 4 account one of them is not my its ur

What's that means??

**Comment by ramdan1523** [comment]
Its just a mistake. The txt i copy use his username not my

**Comment by ramdan1523** [comment]
Wait i remember something

**Comment by ramdan1523** [comment]
To join server u don't need to use the compass u can hit the player with the version name

**Comment by ramdan1523** [comment]
There is a way to move and hit entity right?

**Comment by Tnze** [comment]
Yes, but you need to get its EntityID by yourself.

**Comment by ramdan1523** [comment]
Kay

**Comment by ramdan1523** [comment]
I can't find player entity id

**Comment by ramdan1523** [comment]
I see you in lobby did it work

**Comment by Tnze** [comment]
MscBaiMeow is working on it. It is necessary to update the go-mc version 1.14.1 partially if we need to login your server.

**Comment by ramdan1523** [comment]
I am not 100% understand

**Comment by Tnze** [comment]
That's not a easy way for you. However, you would like to ask MscBaiMeow for help.

**Comment by ramdan1523** [comment]
OK

**Comment by MscBaiMeow** [comment]
It's OK now.

**Comment by MscBaiMeow** [comment]
``` go
package main

import (
	"fmt"
	"math"
	//"github.com/google/uuid"
	"time"
	"log"
	"bufio"
	"github.com/Tnze/go-mc/bot"
	"github.com/Tnze/go-mc/chat"
	"os"
	// "github.com/Tnze/go-mc/authenticate"
)

var (
	c *bot.Client
	YawNow float32
	PitchNow float32
)

func main() {
	c = bot.NewClient()
	c.Auth = bot.Auth{
		Name: "Msc_BaiMeow",
	}
	// For online-mode, you need login your Mojang account
	// and load your Name and UUID to client:
	//
	//      auth, err := authenticate.Authenticate("Your E-mail", "Your Password")
	//      if err != nil {
	//              panic(err)
	//      }
	//      c.Name, c.Auth.UUID, c.AsTk =  auth.SelectedProfile.Name, auth.SelectedProfile.ID, auth.AccessToken

	//Login
	err := c.JoinServer("www.ironcreeper.com", 25565)
	if err != nil {
		log.Fatal(err)
	}
	log.Println("Login success")
	//Regist event handlers
	//c.Events.EntityID = onEID
	c.Events.GameStart = onGameStart
	c.Events.ChatMsg = onChatMsg
	c.Events.Disconnect = onDisconnect
	c.Events.PluginMessage = onPluginMessage

	//JoinGame
	go sendChat()
	//go printxz()
	go join()
	err = c.HandleGame()
	if err != nil {
		log.Fatal(err)
	}
}
//was used to get EntityID
//func onEID(eid int, name [16]byte,x float64) error {
//	log.Println(eid)
//	log.Println("name")
//	log.Print(uuid.UUID(name))
//	log.Println("X:")
//	log.Print(x)
//	return nil
//}

func join() {
	time.Sleep(time.Second*5)
	for int(c.X) != 124 {
	TweenLookAt(c,124,91,214,time.Second*1)
	time.Sleep(time.Second*3)
	TweenLineMove(c,124,214)
	}
	TweenLookAt(c,126.5,91,214.5,time.Second*1)
	err := c.UseEntity(41,0)
	if err != nil{
		log.Print(err)
	}
}

func sendChat() {
	console := bufio.NewScanner(os.Stdin)
	for console.Scan() {
		err := c.Chat(console.Text())
		if err != nil {
			log.Println(err)
		}
	}
}

func onGameStart() error {
	time.Sleep(time.Second*2)
	if err := c.Chat("/login 123654"); err != nil {
		return err
	}
	log.Println("Game start")

	return nil //if err isn't nil, HandleGame() will return it.
}

func onChatMsg(c chat.Message, pos byte) error {
	log.Println("Chat:", c)
	return nil
}

func onDisconnect(c chat.Message) error {
	log.Println("Disconnect:", c)
	return nil
}

func onPluginMessage(channel string, data []byte) error {
	log.Println("PluginMessage", channel, data)
	return nil
}

func TweenLookAt(g *bot.Client, x, y, z float64, t time.Duration) {
	x0, y0, z0 := g.X, g.Y, g.Z
	x, y, z = x-x0, y-y0, z-z0

	r := math.Sqrt(x*x + y*y + z*z)
	yaw := -math.Atan2(x, z) / math.Pi * 180
	for yaw < 0 {
		yaw = 360 + yaw
	}
	pitch := -math.Asin(y/r) / math.Pi * 180
	YawNow=float32(yaw)
	PitchNow=float32(pitch)
	TweenLook(g, float32(yaw), float32(pitch), t)
}

// TweenLook do tween animation at player's head.
func TweenLook(g *bot.Client, yaw, pitch float32, t time.Duration) {
	start := time.Now()
	yaw0, pitch0 := g.Yaw, g.Pitch
	ofstY, ofstP := yaw-yaw0, pitch-pitch0
	var scale float32
	for scale < 1 {
		scale = float32(time.Since(start)) / float32(t)
		g.SetLook(yaw0+ofstY*scale, pitch0+ofstP*scale, true)
		time.Sleep(time.Millisecond * 50)
	}
}

//TweenLineMove allows you smoothly move on plane. You can't move in Y axis
func TweenLineMove(g *bot.Client, x, z float64) error {
	start := time.Now()
	x0, y0, z0 := g.X, g.Y, g.Z

	if similar(x0, x) && similar(z0, z) {
		return nil
	}

	y0 = math.Floor(y0)
	ofstX, ofstZ := x-x0, z-z0
	t := time.Duration(float64(time.Second) * (math.Sqrt(ofstX*ofstX+ofstZ*ofstZ) / 5))
	var scale float64
	for scale < 1 {
		scale = float64(time.Since(start)) / float64(t)
		g.SetPos(x0+ofstX*scale, y0, z0+ofstZ*scale, true)
		time.Sleep(time.Millisecond * 50)
	}

	if !similar(g.X, x) || !similar(g.Z, z) {
		return fmt.Errorf("wrongly move")
	}
	return nil
}

func similar(a, b float64) bool {
	return a-b < 1 && b-a < 1
}
```

**Comment by MscBaiMeow** [comment]
Beside this you should also change  tnze/go-mc/bot/motion.go
add
```go
func (c *Client) UseEntity(entityID int32, hand int) error {
	return c.conn.WritePacket(pk.Marshal(
		data.UseEntity,
		pk.VarInt(entityID),
		pk.VarInt(0),
		pk.VarInt(hand),
	))
}

func (c *Client) SetPos(x float64, y float64, z float64, ground bool) error {
	return c.conn.WritePacket(pk.Marshal(
		data.PlayerPosition,
		pk.Double(x),
		pk.Double(y),
		pk.Double(z),
		pk.Boolean(ground),
	))
}

func (c *Client) SetLook(Yaw float32, Pitch float32, ground bool) error{
	return c.conn.WritePacket(pk.Marshal(
		data.PlayerLook,
		pk.Float(Yaw),
		pk.Float(Pitch),
		pk.Boolean(ground),
	))
}
```

**Comment by MscBaiMeow** [comment]
Then you can join the server.

**Comment by ramdan1523** [comment]
TY

**Comment by ramdan1523** [comment]
Error

command-line-arguments
./daze.go:170:2: invalid character U+0040 '@'
./daze.go:170:3: syntax error: non-declaration statement outside function body

**Comment by ramdan1523** [comment]
Actually i copy it wrong

**Comment by ramdan1523** [comment]
This error comes after fixing 

./daze.go:124:2: undefined: YawNow
./daze.go:125:2: undefined: PitchNow

**Comment by ramdan1523** [comment]
To what should i change the yawnow?

**Comment by MscBaiMeow** [comment]
Sorry,please detele line 124 and line 125

**Comment by ramdan1523** [comment]
Can u just say u edit the comment aboce because its not easy to find that line

**Comment by MscBaiMeow** [comment]
233

**Comment by ramdan1523** [comment]
?

**Comment by ramdan1523** [comment]
Does download the 1.14.3 but change the data folder to 1.14.1 delete the slot bug

**Comment by MscBaiMeow** [comment]
No

**Comment by ramdan1523** [comment]
I didn't read change ingame to fix bug

**Comment by ramdan1523** [comment]
But after i delete it, it say undefined disconnect

**Comment by MscBaiMeow** [comment]
Maybe you detele something wrongly

**Comment by ramdan1523** [comment]
> To fix this bug, simply remove this line :)
> 
> https://github.com/Tnze/go-mc/blob/bfb5e51f243fa6db1e598c61788e7f437c283caf/bot/ingame.go#L121
> 
> 
> Fork v1.14.1 and do it.

**Comment by MscBaiMeow** [comment]
What he said is true,and I removed line 121 ,too.

**Comment by ramdan1523** [comment]
Wrong lines sry

**Comment by MscBaiMeow** [comment]
Maybe you should try to download ingame.go again and change it in the same say again.

**Comment by ramdan1523** [comment]
Yes i did that

**Comment by ramdan1523** [comment]
Is the move instant because the server kick me for unexpected move

**Comment by ramdan1523** [comment]
And the command stuck

**Comment by MscBaiMeow** [comment]
Server always kick it for unexpected move,but I have tried my best to let it move smoothly.

**Comment by ramdan1523** [comment]
Hmmm

**Comment by MscBaiMeow** [comment]
What "command stuck" means?
I login in the server and I can chat

**Comment by ramdan1523** [comment]
I can't disconnect

**Comment by MscBaiMeow** [comment]
Use ctrl+c to close it......

**Comment by ramdan1523** [comment]
What does the join func timer do

**Comment by ramdan1523** [comment]
What does the join func timer do

**Comment by ramdan1523** [comment]
Does time sleep then tween move then time sleep then tween move work

Because u don't get kicked for teleporting 0.5 block

**Comment by MscBaiMeow** [comment]
the first timer is used to wait load the map data
as for the second timer, you can remove it

**Comment by MscBaiMeow** [comment]
tween move always cut by the server

**Comment by ramdan1523** [comment]
I found out what happen

**Comment by ramdan1523** [comment]
Its not to fast

**Comment by ramdan1523** [comment]
Its too far

**Comment by ramdan1523** [comment]
Msc use the bot in my server 
Tnze look at what th

**Comment by ramdan1523** [comment]
The bot

**Comment by Tnze** [comment]
Let me see...... I recommend clicking on the window rather than move and right-click player to log in, which sends fewer packets. I suppose it's just send [Use Item](https://wiki.vg/Protocol#Use_Item) and [Click Window](https://wiki.vg/Protocol#Click_Window) .
> Although I'd like to help, I've been very busy lately. Very sorry about that.

**Comment by ramdan1523** [comment]
Actually not right click but left click

**Comment by ramdan1523** [comment]
Tnze is right since player actually spawn randomly in 5 x 5 square

**Comment by Tnze** [comment]
> Actually not right click but left click

Then use [Attach Entity](https://wiki.vg/Protocol#Attach_Entity) instead

**Comment by ramdan1523** [comment]
I rly hope i understand the program so i can change it easier

**Comment by ramdan1523** [comment]
I mean attack why attach

**Comment by Tnze** [comment]
> I mean attack why attach

I have no idea. Don't care about it

**Comment by MscBaiMeow** [comment]
Your server request that right click to enter the  server,isn't attack.

**Comment by ramdan1523** [comment]
IDK anymore

**Comment by Tnze** [comment]
I think this issue is solve.
But you still could open a new one if you have any question.

**Comment by ramdan1523** [comment]
What is the click window command

**Comment by ramdan1523** [comment]
I write c.ClickWindow it doesn't work

**Comment by ramdan1523** [comment]
I found out u need to add code in bot/motion.go

**Comment by ramdan1523** [comment]
Is this right? 
(func (c *Client) ClickWindow(slot int) error {
        return c.conn.WritePacket(pk.Marshal(
                data.ClickWindow,
                pk.VarInt(slot),
        ))
}
)

**Comment by ramdan1523** [comment]
> func (c *Client) ClickWindow(slot int) error {
        return c.conn.WritePacket(pk.Marshal(
                data.ClickWindow,
                pk.VarInt(slot),
        ))
}

>

**Comment by Tnze** [comment]
Almost right, 
but you know I will only add it on the v1.14.4 if I do

**Comment by ramdan1523** [comment]
I just need the code

**Comment by Tnze** [comment]
![)(K_(V_}F2TRHX8S0 L ~{Y](https://user-images.githubusercontent.com/19628575/62823272-16147600-bbc2-11e9-9554-87ff454c7203.jpg)
I didn't write that code.
Check [it](https://wiki.vg/Protocol#Click_Window) for yourself if you are in a hurry.

**Comment by ramdan1523** [comment]
I think i need to change (slot int) to something else

**Comment by ramdan1523** [comment]
My server is updated to 1.14.4

**Comment by ramdan1523** [comment]
What is the command to swing arm
