### ISSUE TITLE
Bedrock edition support?

### ISSUE THREAD

**Issue by k0ngk0ng** [Tnze/go-mc#70]
Does this library support Bedrock edition?

If not, is there any plan to support it?  

thanks

**Comment by Tnze** [comment]
No...
Sorry about that I have no plan to support BE or any old version of JE.

It's hard work to be compatible with all versions at the same time. I can only try to keep up with the latest Java Edition at the moment.

**Comment by crthpl** [comment]
For Bedrock Edition, you should check out gophertunnel: https://github.com/Sandertv/gophertunnel
