### ISSUE TITLE
Create 'Extra' text outside of the 'chat' package?

### ISSUE THREAD

**Issue by ubergeek77** [Tnze/go-mc#76]
I am fairly new to Go, so I may be missing a workaround way of doing this, but it does not seem possible to create `chat.Message` objects containing `Extra` contents without modifying the `chat` package.

For instance, consider this `chat.Message` object with additional formatting, containing an `Extra` block with its own formatting:

```
desc := chat.Message{
	Text: "Line 1\n",
	Color: "blue",
	Italic: true,
	Extra: []chat.jsonChat{{
		Text: "Line 2",
		Color: "green",
		Bold: true,
	}},
}
```

This will result in the following compiler error:

`cannot refer to unexported name chat.jsonChat`

If you were to replace `jsonChat` with `Message`, which *is* exported, you would get another compiler error:

`cannot use []chat.Message literal (type []chat.Message) as type []chat.jsonChat in field value`

This makes sense; even though `Message` is identical to `jsonChat`, because they are considered distinct types, this is not possible.

However, if you were to export `jsonChat` by captializing it, this becomes possible:

```
desc := chat.JsonChat{
	Text: "Line 1\n",
	Color: "blue",
	Italic: true,
	Extra: []chat.JsonChat{{
		Text: "Line 2",
		Color: "green",
		Bold: true,
	}},
}
```

However, this requires modifying `go-mc/chat/chatMsg.go`. I would rather not modify this package directly, since it complicates development somewhat. It surely makes Docker builds much more complicated than simply `go get`-ing your package.

My use case for this is displaying formatted server messages to Minecraft clients in the server list. I am using `go-mc` to create a "stub" Minecraft server, which will be shown to my players when the real Minecraft server is offline. When no players are online, I want to shut down or "hibernate" my Minecraft server. Then, if a player tries to view the server when the real Minecraft server is offline, they will see messages created in the "stub" server I am writing in Go using `go-mc`. A player connecting to this "stub" server launches a request to start the real Minecraft server, which will shift the IP address to the real server and allow them to play.

In fact, using `go-mc`, and the above example code (after modifying `chatMsg.go`), I was able to create this stub server:

![Example](https://user-images.githubusercontent.com/3455585/92824595-23e88c00-f3be-11ea-8021-73ecc0bedf33.PNG)

While I can create two lines by simply including a `\n` in the main `Text` block, I enjoy how easy color and text formatting is with `go-mc`, and I would like to create lines of text with independent formatting from one another.

Is there a workaround to do this without modifying `chatMsg.go`? Or can `jsonChat` possibly be made public in a future release of `go-mc`?

Thanks!

---

(P.S. When writing this issue, I noticed a bug in the way `go-mc` formats messages. In my above example code, I set "Line 1" to `Italic: true`. However, as you can see from the screenshot, it is not italicized. Bold and Obfuscated formatting works, but not Italic. I have set text to be italicized in server messages before, so I know it is possible to do this. Perhaps this belongs in its own issue?)

**Comment by Tnze** [comment]
That's a problem, maybe you could temporarily use `func (*Message) UnmarshalJSON `instead ?

**Comment by Tnze** [comment]
I was thinking about exporting jsonmsg and message at the same time, which was strange and confusing

**Comment by ubergeek77** [comment]
> I think exporting jsonMsg and Message at the same time was strange and confusing

Yes, I agree. But since `jsonChat.Extra` requires the `jsonChat` specifically, which is not exported, I couldn't find a way to make that particular example work.

Perhaps it would be easier to remove `jsonChat` and just replace it with `Message`? This only requires changes to a few lines in `chatMsg.go`, and since `jsonChat` is never exported, and `Message` is identical to that type, this isn't a breaking change (at least I don't think it is). I'm not exactly sure what the second type copy is really doing.

As for the sample code you suggested, that uses `Append`, it actually produces invalid JSON (maybe I'm doing something wrong? My code works with my previous examples):

```
{
  "version": {
    "name": "1.16.2",
    "protocol": 751
  },
  "players": {
    "online": 0,
    "max": 20
  },
  "description": {
    "extra": [
      {},
      {},
      {
        "text": "Line 1\n",
        "italic": true,
        "color": "blue"
      },
      {
        "text": "Line 2",
        "bold": true,
        "color": "green"
      }
    ]
  }
}
```

While we're on the subject, I should mention that setting formatting in JSON like this doesn't seem to work correctly on server list descriptions.

Take this code for instance, which adds the change I suggested above, renaming `jsonChat` to `Message`:

```
desc := chat.Message{
	Text: "Line 1\n",
	Color: "aqua",
	Bold: true,
	Extra: []chat.Message{{
		Text: "Line 2",
		Color: "white",
		Bold: false,
		UnderLined: true,
	}},
}
```

As you can see, I set Bold to `true` for `Text`, and to `false` for `Extra`. The second line becomes Bold when it should not be:

![Example2](https://user-images.githubusercontent.com/3455585/92846313-7da98000-f3d7-11ea-9944-f83a12bbdc2e.PNG)

I don't know if this is a Minecraft bug, or a `go-mc` bug. But I think it's due to using the [raw JSON format](https://minecraft.gamepedia.com/Raw_JSON_text_format#Formatting) instead of [formatting codes](https://minecraft.gamepedia.com/Formatting_codes#Formatting_codes). I don't think the server list supports the raw JSON format completely.

I see that `chatMsg.go` has plenty of code already written to apply formatting codes. Is there any way to get it to use those instead of the raw JSON format?

**Comment by Tnze** [comment]
> I'm not exactly sure what the second type copy is really doing.

This is a compromise for the JSON standard library. You could try to replace it, then you know why I write this.

**Comment by ubergeek77** [comment]
> This is a compromise for the JSON standard library. You could try to replace it, then you know why I write this.

Ah, I see. Then perhaps for my use case (only server messages), it doesn't cause any issues. Because I actually made that replacement for the above screenshot and it works. But it's possible doing more complex things would be incompatible with such a change.

**Comment by Tnze** [comment]
> As you can see, I set Bold to true for Text, and to false for Extra. The second line becomes Bold when it should not be

Looks like is my fault. I'm a little busy right now. I'll check it later.

**Comment by Tnze** [comment]
Could you please have a try of this? :

```go
desc := chat.Message{
	Extra: []chat.Message{{
		Text: "Line 1\n",
		Color: "aqua",
		Bold: true,
	},{
		Text: "Line 2",
		Color: "white",
		Bold: false,
		UnderLined: true,
	}},
}
```

I thought about the mechanism of JSON messages, but there was no environment for testing
