### ISSUE TITLE
Refactor of the bot.Client API ?

### ISSUE THREAD

**Issue by twitchyliquid64** [Tnze/go-mc#78]
Would you be open to me submitting PRs to refactor `bot.Client` ? This is what I would like to do:

1. Move specific packet serialization/deserialization logic out of `bot/ingame.go` into its own types, in their own package. I could put them into `net/packet` if you are okay with that, otherwise I can make another package for these high-level packet types.

2. Move entity tracking and world/block tracking logic out of `bot.Client`, instead having bot.Client consume an interface for such tracking. This would allow users to switch out different 'backends' for tracking entities and chunk data, and allow us to be more modular in the underlying implementation.

3. Implement missing player state variables and tracking into `bot.Client`. Specifically, that would be `Move()` / `Look()` methods, as well as methods for manipulating the inventory.

**Comment by Tnze** [comment]
Sorry for the delay, my net access are quite not good this days. Your ideas sounds greate and I want to refactor the `bot` package for a long time.

Actually, I had created a github organization go-mc at [github.com/go-mc](https://github.com/go-mc). You can write a bot package according to your ideas, and then I will fork it there.

**Comment by twitchyliquid64** [comment]
Sounds good! Im making big changes in my fork at https://github.com/twitchyliquid64/go-mc. Ive gotten the chunk/chunk update /multi-chunk update thingy working again for 1.16.3, my next big task is getting entities working again and updating the item dictionary in the data package.

**Comment by Tnze** [comment]
Well, I mean, is it better to treat the `bot` package as a separate repo ?

**Comment by twitchyliquid64** [comment]
I think it makes sense to move the data (blocks / item / entity dictionaries) into its own repo, but im inclined to keep the logic together (packets, bot, client, chunk handling) in the same repo.

**Comment by twitchyliquid64** [comment]
PTAL at #84.
