### ISSUE TITLE
EOF when writing packet

### ISSUE THREAD

**Issue by crthpl** [Tnze/go-mc#86]
I have used the simpleServer and daze examples, and made it so that every time the client sends a packet, the server responds with a chat message:
```
for {
		if _, err := conn.ReadPacket(); err != nil {
			log.Printf("ReadPacket error: %v, Time: %v\n", err, time.Now().Nanosecond())
			break
		}
		// KeepAlive packet is not handled, so client might
		// exit because of "time out".
		conn.WritePacket(pk.Marshal(data.ChatClientbound,
			chat.Message{Text:"hello"},
			pk.Byte(0),
		))
	}
```
I have made no other changes to the original simpleServer other than the above.

However, as soon as the client sends a packet, it disconnects:
Client fatal log:
```
2020/10/16 17:36:33 handle packet 0xE error: EOF
```
Server disconnect log:
```
2020/10/16 17:36:39 ReadPacket error: EOF
```

using `time.Now().Nanosecond()`, I have found out that the server prints it before the client, although I do not know if this is reliable.
Here are the two ouptuts: (note that these are just numbers in the range of [0, 999999999] and resets every second, though they are the same across different programs)
server:
`530846000`
client
`530859000`

**Comment by Tnze** [comment]
Packet content is not updated in simpleServer: https://github.com/Tnze/go-mc/blob/0af0377a4ff25de4e24ab192f5b1987432ccf0ee/cmd/simpleServer/main.go#L142

Is there a way to encode it by `ptypes.JoinGame` ? @twitchyliquid64

**Comment by twitchyliquid64** [comment]
`JoinGame` can be easily extended:

```go
func (p *JoinGame) Encode() pk.Packet {
	return pk.Marshal(
		data.Login,
		p.PlayerEntity,
		p.Hardcore,
		p.Gamemode,
		p.PrevGamemode,
		p.WorldCount,
		p.WorldNames,
		p.Dimension,
		p.WorldName,
		p.HashedSeed,
		p.maxPlayers,
		p.ViewDistance,
		p.RDI,
		p.ERS,
		p.IsDebug,
		p.IsFlat,
	)
}
```

The issue is the entire simpleServer example looks very out of date and needs to be updated. Theres a lot if fields there I don't know what to fill in with, and a few other packets that need revision too.

**Comment by Tnze** [comment]
I am trying to add a new type `pk.Array` and can be used like this:

```go
var (
	count pk.Int
	array []pk.NBT,
)

// Implemented in go-mc
// counter should be a pointer of an integer, for example *int, *pk.Long, *pk.VarInt
// array must be a slice of any type implement `pk.FieldDecoder` and `pk.FieldEncoder`
// or the Decode or Encode method will panic.
func ArrayOf(counter, array interface{}) Array

func Decode() {
	p.Scan(......., &count, pk.ArrayOf(&count, &array), .......)
}

func Encode() {
 	pk.Marshal(pid,
		count,
		pk.ArrayOf(&count, &array),
	)
```

I have no idea to determine if this is a good practice. What do you think?

**Comment by Tnze** [comment]
For more details, the definition of `pk.Array` is like this:

```go
type Array {
	count reflect.Value
	array reflect.Value
}
func (a Array) Decode(r DecodeReader) error
func (a Array) Encoder() []byte
```

**Comment by twitchyliquid64** [comment]
Would just writing a literal Go array of the correct type work?

```go
type Packet struct {
  Field [8]pk.Int
}
```

And then the reflection that handles serializing can detect the array condition and handle appropriately?

**Comment by theoo3** [comment]
> `JoinGame` can be easily extended:
> 
> ```
> func (p *JoinGame) Encode() pk.Packet {
> 	return pk.Marshal(
> 		data.Login,
> 		p.PlayerEntity,
> 		p.Hardcore,
> 		p.Gamemode,
> 		p.PrevGamemode,
> 		p.WorldCount,
> 		p.WorldNames,
> 		p.Dimension,
> 		p.WorldName,
> 		p.HashedSeed,
> 		p.maxPlayers,
> 		p.ViewDistance,
> 		p.RDI,
> 		p.ERS,
> 		p.IsDebug,
> 		p.IsFlat,
> 	)
> }
> ```

Something that the `JoinGame` struct does not have is the Dimension Codec (Vanilla shown [here](https://paste.gg/p/KennyTV/ad46ef552c6443cc808385f060564550)) 
https://github.com/Tnze/go-mc/blob/0af0377a4ff25de4e24ab192f5b1987432ccf0ee/net/ptypes/world.go#L15
This is probably because `ptypes.NBT` does not satisfy `pk.Field` I don't think the Vanilla Client accepts empty fields that are just not included. (Some sort of java netty out of bounds exception) Will/Should this be implemented?

**Comment by Tnze** [comment]
This is closed because this issue is outdated -_-
If you have any questions, please send a new issue 😁
