### ISSUE TITLE
Read Minecraft chat with bot package

### ISSUE THREAD

**Issue by LucasClaisse** [Tnze/go-mc#89]
I am trying to read the chat from my remote application, I tried to use the bot package. I have this piece of code I tried to run:
```go
botClient := bot.NewClient()
err := botClient.JoinServer(server.Address, 25565)
```
I'm running a server on the minecraft version 1.16.4 on the port 25565, and RCON on port 25575 and got this error message:
```
bot: connect disconnected by server: {"translate":"multiplayer.disconnect.outdated_client","with":["1.16.4"]}
```
Any ideas on how to fix it?

**Comment by Tnze** [comment]
go get github.com/Tnze/go-mc@master

**Comment by LucasClaisse** [comment]
Working now, thanks for the fix
