### ISSUE TITLE
Old position packet

### ISSUE THREAD

**Issue by zLupa** [Tnze/go-mc#91]
Hello, this is a question.
Does the `go-mc/net` implement the old position packet format before 1.14?https://wiki.vg/index.phptitle=Data_types&oldid=14345#Position
I couldn't find anything about it in the package.

Also, thanks for the great library!

**Comment by Tnze** [comment]
https://github.com/Tnze/go-mc/blob/0e959dfbc0009925611c26cab0eca4bde4462870/net/packet/types.go#L68-L70
https://github.com/Tnze/go-mc/blob/0e959dfbc0009925611c26cab0eca4bde4462870/net/packet/types.go#L332-L366

**Comment by Tnze** [comment]
No, but there is an implement here which you can consult.
https://github.com/Tnze/gomcbot/blob/2f9bf8d31dcaa3b06a4a0e45c47548509e84439a/packet/packet.go#L96-L105
https://github.com/Tnze/gomcbot/blob/2f9bf8d31dcaa3b06a4a0e45c47548509e84439a/packet/packet.go#L196-L214

PS: This project is basically go-mc before v1.14 (I am not recommending it. go-mc is better even you are working in 1.13)

**Comment by zLupa** [comment]
Ok, thanks!
