### ISSUE TITLE
Decompression problems

### ISSUE THREAD

**Issue by RavMda** [Tnze/go-mc#95]
client.HandleGame stumbles upon EOF in readByte function.

Stack _(i hope it's not confusing)_:
[ReadPacket](https://github.com/Tnze/go-mc/blob/master/bot/ingame.go#L14) -> [ReadFrom](https://github.com/Tnze/go-mc/blob/master/net/packet/packet.go#L79) -> [readByte](https://github.com/Tnze/go-mc/blob/master/net/packet/types.go#L92) -> [io.ReadFull](https://github.com/Tnze/go-mc/blob/master/net/packet/types.go#L138) -> EOF

If you need that piece of code where HandleGame is called:
https://github.com/RavMda/go-bots/blob/main/bot/maidan/maidan.go#L39

**Comment by Tnze** [comment]
Can you provide an minimize example of using my version of go-mc to replicate the problem ?
I will check it later after finish ~~refactoring~~breaking something, which you definitely know about :)

**Comment by RavMda** [comment]
Here you go:
https://gist.github.com/RavMda/baedb284add843b87b8438995b0103ab

![EOF](https://cdn.discordapp.com/attachments/744430106067599362/820305749611380746/WindowsTerminal_m3JapXpcs0.png)

**Comment by Tnze** [comment]
Quick check result: 
    The client sent an invalid packet, and the server disconnected after parsing failure. The problem should be at `github.com/Tnze/go-mc/net/packet.Packet.Pack()`.
