### ISSUE TITLE
Unable to import some packages 

### ISSUE THREAD

**Issue by pythonuntermensh** [Tnze/go-mc#97]
I can't import package Offline :-(
"module github.com/Tnze/go-mc@upgrade found (v1.16.1), but does not contain package github.com/Tnze/go-mc/offline"

**Comment by wildrun0** [comment]
Yeah, same thing

**Comment by Tnze** [comment]
`go get -u github.com/Tnze/go-mc@master`

**Comment by wildrun0** [comment]
sorry for this useless issue
