### ISSUE TITLE
undefined: io.Discard

### ISSUE THREAD

**Issue by Saxy** [Tnze/go-mc#99]
type: bug
steps to reproduce: 
clone project 
checkout master
start server in examples/simpleServer by running go run main.go

expected: 
server up and running

actual behavior: 
error: ../../nbt/read.go:384:24: undefined: io.Discard

may also used in other files ... need to be checked

io.Discard does not exists ioutil.Discard

OS: macOS Big Sur
go version: 1.16

**Comment by Tnze** [comment]
`ioutil.Discard` is moved to `io.Discard` as of Go 1.16
You are not using Go 1.16
